### ISSUE TITLE
How to subscriber under any topic or subscriber so we get the value published by the publisher?

### ISSUE THREAD

**Issue by DhavalRKansara** [google/googleapis.dart#103]
Using this library how to subscriber under any topic for getting the values which publishers published using google cloud pub-sub?

- Also raised and question on [StackOverflow](https://stackoverflow.com/q/62713503/11724588) as well.

**Comment by kevmoo** [comment]
I'd dig in here: https://cloud.google.com/pubsub/docs/reference/rest
