### ISSUE TITLE
Gmail API 'send' method returning DetailedApiRequestError

### ISSUE THREAD

**Issue by ashtonjonesdev** [google/googleapis.dart#109]
I am rebuilding [my personal website in Flutter](https://github.com/ashtonjonesdev/ashton_jones_dev_website) and need to send an email after a form is filled out

WHAT: I am trying to send an email using the Gmail API Dart library

ERROR: DetailedApiRequestError(status: 400, message: Invalid value at 'message.raw' (TYPE_BYTES), Base64 decoding failed, when calling 'send'

Authentication is working fine. I followed the steps in [googleapis](https://pub.dev/packages/googleapis) package to implement authentication, using a service account and the 'clientViaServiceAccount' method.

I followed the [Gmail API documentation for sending an email using the send method](https://developers.google.com/gmail/api/guides/sending#python_1), creating a MimeMessage, encoding it to base64, creating a Message object and setting the 'raw' property to the encoded MimeMessage, and calling the GmailAPIs 'send' method.

The issue seems to be with the encoding of the MimeMessage.

I created a MimeMessage using [enough_mail package](https://pub.dev/packages/enough_mail) and set the message the Base 64 encoding

Here is a link to the project on Github: https://github.com/ashtonjonesdev/ashton_jones_dev_website The 'send' method is in [consulting.dart](https://github.com/ashtonjonesdev/ashton_jones_dev_website/blob/master/lib/ui/widgets/consulting_tab.dart)

Send email code:
`  
  
 sendEmail() async {
    print('sendEmail');

    // Create a Mime Message and encode it using base64

    MessageBuilder messageBuilder = MessageBuilder();

    messageBuilder.from = [
      MailAddress('Ashton Jones', 'ashton@grapeworks.dev')
    ];

    messageBuilder.to = [MailAddress('Ashton Jones', 'ashton@grapeworks.dev')];

    messageBuilder.subject = 'cool subject';

    messageBuilder.text = 'cool text';

    messageBuilder.encoding = MessageEncoding.base64;

    MimeMessage mimeMessage2 = messageBuilder.buildMimeMessage();

    // TODO: Figure out if I need to encode the entire MimeMessage as a base 64 String here again (I already set the encoding of the MimeMessage to base64 on line 156)

    // Create a Message object and set the 'raw' property to the encoded String
    Message message = Message();

    // TODO Need to set the 'raw' property as the entire encoded MimeMessage
    message.raw = mimeMessage2.renderMessage();

    print('Encoded message: ${message.raw}');

    print(_gmailApi.users);

    // Send the email using the Gmail API 'send' method
    // TODO: When I run this, I get an 'invalid value at 'message.raw' (TYPE_BYTES), Base64 decoding failed' error
    Message messageCompleted =
        await _gmailApi.users.messages.send(message, 'me').catchError((error) {
      print(error);
    });

    print(messageCompleted);
  }`

initState code:
`  @override
  void initState() {
    super.initState();

    print(
        'CREDENTIALS: Client ID: ${_credentials.clientId.toString()} | Client Secret: ${_credentials.privateKey}');

    // Authenticate the credentials with the service account and use them to initialize the GmailAPI
    clientViaServiceAccount(_credentials, scopes).then((AuthClient httpClient) {
      _gmailApi = GmailApi(httpClient);

      print('Users: ${_gmailApi.users}');
    });
  }`

**Comment by Aia-Ashraf** [comment]
I face same error message for BigQuery API when select any field 
I tried to search about any documentations for this but I cann't found 

Simply I want to make selection for BigQuery

**Comment by kevmoo** [comment]
I'd dig in here: https://developers.google.com/gmail/api/reference/rest/v1/users.messages#Message
