### ISSUE TITLE
Google Admob Api - could not authenticate

### ISSUE THREAD

**Issue by keochansothea** [google/googleapis.dart#168]
Hello, I need help to check solution to call google admob api which it is still issue with authentication while calling.

final _credentials = new ServiceAccountCredentials.fromJson(r'''
{
  "type": "service_account",
  "project_id": "xxx",
  "private_key_id": "xxx",
  "private_key": "xxx",
  "client_email": "xxx",
  "client_id": "xxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "xxx"
}
''');

const _SCOPES = const [AdMobApi.admobReadonlyScope, AdMobApi.admobReportScope];

var client = await clientViaServiceAccount(_credentials, _SCOPES);
var adMob = new AdMobApi(client);

var account = await adMob.accounts.list();

ERROR:

status: 401, message: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential.

**Comment by chuongdevJC** [comment]
i faced this bug: ```  Unhandled Exception: Invalid argument(s): Error while extracting private key from DER bytes: Invalid argument(s): Invalid DER encoding: Unexpected tag 51 at offset 0 (end: 616). ``` when try to get admob report.

**Comment by chuongdevJC** [comment]
Did u resolve this issue sir?

**Comment by keochansothea** [comment]
No.

**Comment by chuongdevJC** [comment]
> No.

I resolved this. i used clientViaUserConsent

**Comment by keochansothea** [comment]
I tried this but not working. Could you share me the code?

**Comment by keochansothea** [comment]
Oh no, I tried clientViaServiceAccount but not working.

**Comment by keochansothea** [comment]
using clientViaUserConsent will need intervention from user or not?

**Comment by chuongdevJC** [comment]
> using clientViaUserConsent will need intervention from user or not?

it's like clientViaServiceAccount but get permission through web.

**Comment by keochansothea** [comment]
this is not I want. I want to automated way that dont require action from user.

**Comment by keochansothea** [comment]
the purpose of using clientViaServiceAccount is to not getting intervention from user but google seems to disabled this feature for admob api.

**Comment by chuongdevJC** [comment]
> the purpose of using clientViaServiceAccount is to not getting intervention from user but google seems to disabled this feature for admob api.

I dont get it. U want to get admob report data right?

**Comment by kevmoo** [comment]
Are you sure you've enabled the API for the corresponding service account?
