### ISSUE TITLE
Separate upload of discoveryapis_generator to pub.dev

### ISSUE THREAD

**Issue by remonh87** [google/googleapis.dart#188]
Previously you uploaded the discoveryapis_generator to pub dev. This is very useful since I can use pub global activate on our CI. However the null-safe version of v1.0.0. is not yet published. Is it possible to also publish a new version of this one to pub.dev?

for reference: https://pub.dev/packages/discoveryapis_generator.

**Comment by kevmoo** [comment]
Happy to!

**Comment by kevmoo** [comment]
Sadly, we have to wait for `dart_style` to migrate so I can publish this.

```
Package validation found the following error:
* lib/src/generated_googleapis/discovery/v1.dart is declaring language version 2.12 that is newer than the SDK constraint 2.11 declared in `pubspec.yaml`.
Sorry, your package is missing a requirement and can't be published yet.
For more information, see: https://dart.dev/tools/pub/cmd/pub-lish.
```

**Comment by remonh87** [comment]
@kevmoo  I noticed dart_style is migrated now. Would be great if you can give it another try :)

**Comment by kevmoo** [comment]
Likely won't get to it this week. Quite busy.

**Comment by remidenele** [comment]
That would be awesome if you can find some time to publish the 1.0.0 to pub.dev :crossed_fingers:?

**Comment by remonh87** [comment]
@kevmoo  do you think you have some time coming days to publish  the discovery_apis_generator to pub dev ?

**Comment by kevmoo** [comment]
Uploaded!
