### ISSUE TITLE
Hard-wire in google photos API

### ISSUE THREAD

**Issue by kevmoo** [google/googleapis.dart#190]
The API is not listed in the discovery doc, but it's here: https://photoslibrary.googleapis.com/$discovery/rest?version=v1

**Comment by kevmoo** [comment]
Need to talk to the photos team, first.

**Comment by DisDis** [comment]
Any updates? I generated API for PhotoApi. It works fine. I don't see any obstacles for generate it.

**Comment by kevmoo** [comment]
Sadly, no. We can only publish APIs that are advertised in the discovery document list. Sorry.

**Comment by kevmoo** [comment]
This is documented! https://developers.google.com/photos/library/reference/rest

Going to reopen. This is clearly not hidden in any real way!

**Comment by kevmoo** [comment]
Shipped in v8.1.0

**Comment by DisDis** [comment]
After migrate from googleapis 13.0.0 to 14.0.0. Photos Library API disappeared from the api.
But Photos Library API is public and available at the link ( https://photoslibrary.googleapis.com/$discovery/rest?version=v1 )

**Comment by kevmoo** [comment]
@DisDis – we had to move to a model where all of the API definitions are hosted on GitHub and reviewed.

You're always welcome to take all of the tech here and roll your own package, but we can't do that any more.
