### ISSUE TITLE
Null-safe typing prevents clearing of File properties in Drive v3

### ISSUE THREAD

**Issue by wesleym** [google/googleapis.dart#200]
With googleapis 2.0.0 with sound null safety enabled, there no longer seems to be a way to clear a property from a File.

Previously working code:

```await driveApi.files.update(File()..properties = {showId: null}, driveFileId)```

The googleapis library for Drive v3 has a File type with a set of key-value pairs named `properties`: https://pub.dev/documentation/googleapis/latest/drive.v3/File/properties.html. This matches the underlying Drive v3 API documentation: https://developers.google.com/drive/api/v3/reference/files/update#properties. The documentation for both are shared:

> Entries with null values are cleared in update and copy requests.

As of googleapis 2.0.0, the type of `properties` is `Map<String, String>?`, which prevents setting a value to null. As a result, there seems to be no way to clear a property.

This issue also affects the `appProperties` property.

**Comment by kevmoo** [comment]
Ah! That's a tough one, @wesleym . Will look...

**Comment by kevmoo** [comment]
See also https://github.com/google/googleapis.dart/issues/211
