### ISSUE TITLE
[Speech] Streaming Recognition API is missing from speech/v1.dart

### ISSUE THREAD

**Issue by Pacane** [google/googleapis.dart#222]
As the title says, streaming recognition isn't available at the moment in Dart, but I believe it's supported by other languages.

Is there a way to add it? Otherwise can someone from outside google like me clone this repo and re-generate the code based on the up-to-date APIs?

[Here are the end point (and configs) I'm looking for](https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#google.cloud.speech.v1.StreamingRecognizeRequest).

Thank you!

**Comment by kevmoo** [comment]
This package only exposes the REST API - https://cloud.google.com/speech-to-text/docs/reference/rest

Sadly, the API you're looking for under the RPC API – you'd have to dig in and figure out how to use gRPC, I think.
