### ISSUE TITLE
Failed assertion: line 96 pos 16: 'credentials.refreshToken != null': is not true

### ISSUE THREAD

**Issue by drScripts** [google/googleapis.dart#225]
Hello i just use clientViaUserConsent to get the access token to the googleapis and i just get the error it said `E/flutter ( 4723): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:googleapis_auth/src/auth_http_utils.dart': Failed assertion: line 96 pos 16: 'credentials.refreshToken != null': is not true.`. but at browser said if i has obtained access credential. im using googleapis_auth version 1.1.0

**Comment by kevmoo** [comment]
If you're using Flutter, please use https://pub.dev/packages/google_sign_in

See the documentation here: https://flutter.dev/docs/development/data-and-backend/google-apis
