### ISSUE TITLE
googleapis_auth Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by rlfolden** [google/googleapis.dart#226]
I am trying to use the googleapis_auth 1.1.0 package from a macos desktop app, using some of the sample code.

void prompt(String url) async {
              if (await canLaunch(url)) {
                await launch(url);
              } else {
                throw 'Could not launch $url';
              }
            }

            var id = ClientId(
                "-----my client id ---------------.apps.googleusercontent.com",
                null);
            var scopes = ['https://mail.google.com/'];

            var client = http.Client();
            await obtainAccessCredentialsViaUserConsent(
                    id, scopes, client, prompt)
                .then((AccessCredentials credentials) {
              print('=============  ${credentials.toString()}');
              // Access credentials are available in [credentials].
              // ...
              client.close();
            });

The code almost works but I get the following error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
#0      obtainAccessCredentialsUsingCode (package:googleapis_auth/src/oauth2_flows/auth_code.dart:62:62)
#1      AuthorizationCodeGrantAbstractFlow._obtainAccessCredentialsUsingCode (package:googleapis_auth/src/oauth2_flows/auth_code.dart:131:7)
#2      AuthorizationCodeGrantServerFlow.run (package:googleapis_auth/src/oauth2_flows/auth_code.dart:210:19)
<asynchronous suspension>
#3      MyApp.build.<anonymous closure>.<anonymous closure> (package:rudy_googleapis/main.dart)
<asynchronous suspension>

And the browser window jumps someplace and gives me an HTTP ERROR 500 .

Also,  the print statement never executes.

Any ideas?

**Comment by tananga** [comment]
I have something similar : https://github.com/google/googleapis.dart/issues/254

**Comment by kevmoo** [comment]
Which version of the package are you using? This should be fixed in the latest version of googleapis_auth

**Comment by rlfolden** [comment]
googleapis_auth 1.1.0 was what I tested with.

**Comment by kevmoo** [comment]
Ah! That was fixed in https://github.com/google/googleapis.dart/pull/197

Just need to publish the latest googleapis_auth package!
