### ISSUE TITLE
Why should we expose our secret key in this example?

### ISSUE THREAD

**Issue by gOzaru** [google/googleapis.dart#228]
I read this example code on this [github](https://github.com/google/googleapis.dart/blob/master/generated/googleapis/example/main.dart). 
And it asked us to provide secret key inside the dart file. 
Isn't this practice dangerous to be done? 
I thought we should disclose our secret keys in Google Secret Manager???
What is this key supposed to be here?
Please, help me out!

**Comment by jonasfj** [comment]
I would not recommend putting credentials into source code. How those are injected into your application depends on what you're building, who your user is, how it's locked down, etc.

For server applications I usually store secrets in env vars... but if I'm running on GCP I would just use the service account the application already has.. Look at ApplicationDefaultCredentials in `googleapis_auth`.

**Comment by jonasfj** [comment]
Filed -> https://github.com/google/googleapis.dart/pull/229

That's what I would suggest on a server environment.
