### ISSUE TITLE
FirebaseCloudMessagingApi.firebaseMessagingScope missing

### ISSUE THREAD

**Issue by jimmyff** [google/googleapis.dart#237]
`FirebaseCloudMessagingApi` only has `.cloudPlatformScope`, I think it should also have `.firebaseMessagingScope` with value: `'https://www.googleapis.com/auth/firebase.messaging'` according to [the docs](https://firebase.google.com/docs/cloud-messaging/auth-server#use-credentials-to-mint-access-tokens)

**Comment by kevmoo** [comment]
We're going off what's in https://fcm.googleapis.com/$discovery/rest?version=v1 – I'll see if I can file an internal issue.

**Comment by kevmoo** [comment]
Google-internal tracking issue: http://b/190652735

**Comment by kevmoo** [comment]
@jimmyff – this was fixed in the latest release of these APIs. It's also (now) fixed internally.

You found a bug in Google code. Well done! 😄
