### ISSUE TITLE
Cannot create and upload drive files with names containing non-ASCII characters

### ISSUE THREAD

**Issue by dr953** [google/googleapis.dart#238]
Fluter 2.2
_discovery_commons 1.0.0

When using google drive v3 API to create request to create and upload a file to Drive storage:
`
driveApi.files.create(
            drive.File()
              ..name = fileName
              ..parents = [dirId],
            uploadMedia: drive.Media(myFile.openRead(), myFile.lengthSync()));
`

if the file name contains non-ASCII characters, an exception is thrown in multipart_media_uploader.dart: Future<http.StreamedResponse> upload().
The same happens if optional properties are used and they contain non-ASCII characters.

The reason is line 52:
` 
final bodyController = StreamController<List<int>>()
      ..add(ascii.encode(bodyHead));
`

The exception is thrown because `bodyHead` contains filename, or other fields, containing non-ASCII characters.

Instead of ASCII encoding, we should use utf8 encoding and adjust the length calculation to account for that encoding:
`
    final encodedBodyHead = utf8.encode(bodyHead);

    final totalLength = encodedBodyHead.length +
        _lengthOfBase64Stream(_uploadMedia.length!) +
        bodyTail.length;

    final bodyController = StreamController<List<int>>()
      ..add(encodedBodyHead);

`

**Comment by kevmoo** [comment]
Do a `pub upgrade` and you should be good~
