### ISSUE TITLE
BigQuery api to run custom query

### ISSUE THREAD

**Issue by chunhtai** [google/googleapis.dart#241]
I am trying to run custom query that includes where clause and group by clause, but I can only find https://github.com/google/googleapis.dart/blob/master/generated/googleapis/lib/bigquery/v2.dart#L1676
Is there an API to do this?

**Comment by kevmoo** [comment]
https://pub.dev/documentation/googleapis/latest/bigquery.v2/bigquery.v2-library.html

You'd import `package:googleapis/bigquery/v2.dart`

**Comment by chunhtai** [comment]
@kevmoo I did import the package but there is no api to run custom query. For example
select * from `mytable` where id > 0

This is the API doc I was looking at https://pub.dev/documentation/googleapis/latest/bigquery.v2/TabledataResource-class.html

**Comment by chunhtai** [comment]
ah I found https://pub.dev/documentation/googleapis/latest/bigquery.v2/JobsResource/query.html
I think this solve my use case, thanks
