### ISSUE TITLE
Picker API support?

### ISSUE THREAD

**Issue by emiliocantuc** [google/googleapis.dart#250]
hi,
is there a wrapper for the Picker API? can't seem to find it under drive v2 or v3.
are there any plans of supporting it in the future?

thanks

**Comment by kevmoo** [comment]
Can you link to some Google Developer or Google cloud docs on this – just so I know what you're talking about.

**Comment by emiliocantuc** [comment]
Yep:

https://developers.google.com/picker/docs

I believe its just a UI wrapper. I realize packages like file_picker let you pick files from drive if you have drive installed but it would be nice to hace something similar Picker even if it launches on the browser.

**Comment by kevmoo** [comment]
Hey @emiliocantuc 

This API is UI-focused. It's not covered by this package. Sorry.
