### ISSUE TITLE
[YoutubeApi] I have 5 channels on youtube but items parameter returns null

### ISSUE THREAD

**Issue by tananga** [google/googleapis.dart#255]
I have 5 or even 6 channels on my youtube account but YouTube api returns "items" null.

```dart
final data =
        await YouTubeApi(httpClient!).channels.list(['snippet'], mine: true);
    print(data.kind);
    printWrapped(data.toJson().toString());
    if (data.items == null) {
      print("items empty");
    } else {
      print(data.items!.length);
    }
```

OUTPUT looks something like this:
I/flutter (13789): youtube#channelListResponse
I/flutter (13789): {etag: RuuXzTIr0OoDqI4S0RU6n4FqKEM, kind: youtube#channelListResponse, pageInfo: {resultsPerPage: 5, totalResults: 0}}
I/flutter (13789): items empty

I made something wrong ?

**Comment by kevmoo** [comment]
Look through https://developers.google.com/youtube/v3/docs

We don't have details on specific APIs – sorry!
