### ISSUE TITLE
Please add "Discussions" panel.

### ISSUE THREAD

**Issue by tananga** [google/googleapis.dart#256]
Hello. Please add "Discussions" panel on github to have a place where we can freely discuss Google APIs.![Screenshot 2021-07-03 at 23 07 55](https://user-images.githubusercontent.com/44244477/124367094-ac3d6380-dc54-11eb-96f6-00652e0de4d3.png)

**Comment by kevmoo** [comment]
https://github.com/google/googleapis.dart/discussions !
