### ISSUE TITLE
[YoutubeAPI] I don't see a popup to select a youtube chanel

### ISSUE THREAD

**Issue by tananga** [google/googleapis.dart#261]
Hello ;)

When I try to fetch my youtube playlists from https://developers.google.com/youtube/v3/docs/playlists/list?apix=true and I put this as a request:

GET https://youtube.googleapis.com/youtube/v3/playlists?part=snippet&maxResults=25&mine=true HTTP/1.1

Authorization: Bearer [YOUR_ACCESS_TOKEN]
Accept: application/json

I see popup to select one of my many channels and everything is great. I have response type 200 and a full data

![Screenshot 2021-07-05 at 10 49 40](https://user-images.githubusercontent.com/44244477/124444402-d9863080-dd7e-11eb-880f-5087c54786c9.png)

BUT.......

When Im executing the same request from flutter app I don't see a popup and I have DetailedApiRequestError(status: 404, message: Channel not found.)

Can anyone help ? 

Here is the code:

```dart
import 'package:extension_google_sign_in_as_googleapis_auth/extension_google_sign_in_as_googleapis_auth.dart'
    as auth;
import 'package:google_sign_in/google_sign_in.dart';
import 'package:googleapis/people/v1.dart';
import "package:googleapis/youtube/v3.dart";
import 'dart:async';
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Google Sign In',
      home: SignInDemo(),
    ),
  );
}

class SignInDemo extends StatefulWidget {
  @override
  State createState() => SignInDemoState();
}

class SignInDemoState extends State<SignInDemo> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Google Sign In'),
        ),
        body: ConstrainedBox(
          constraints: const BoxConstraints.expand(),
          child: _buildBody(),
        ));
  }

  Widget _buildBody() {
    return ElevatedButton(
      child: const Text('SIGN IN'),
      onPressed: _handleSignIn,
    );
  }

  Future<void> _handleSignIn() async {
    final _googleSignIn = new GoogleSignIn(
      scopes: [
        PeopleServiceApi.contactsReadonlyScope,
        YouTubeApi.youtubepartnerScope,
        YouTubeApi.youtubeForceSslScope,
        YouTubeApi.youtubeScope,
        YouTubeApi.youtubeReadonlyScope,
        YouTubeApi.youtubeChannelMembershipsCreatorScope,
        YouTubeApi.youtubeScope,
        YouTubeApi.youtubepartnerChannelAuditScope,
      ],
    );
    await _googleSignIn.signOut();
    await _googleSignIn.signIn();

    final httpClient = await _googleSignIn.authenticatedClient();
    final YouTubeApi youtubeApi = YouTubeApi((httpClient)!);

    final response = await youtubeApi.playlists.list(
      ["snippet"],
      mine: true,
      maxResults: 25,
    );
    print(response.items!.length);
  }
}

```

**Comment by tananga** [comment]
When I use ApiExplorer on https://developers.google.com/youtube/v3/docs/playlists/list?apix=true I see poput witch my channel lists and after selecting one of them I get a oauth token back which works. When I use this line "final httpClient = await _googleSignIn.authenticatedClient();" with practically All youtube scopes I also get oauth token but when I put it in my YoutubeApi request I get 

"error": {
        "code": 404,
        "message": "Channel not found.",
        "errors": [
            {
                "message": "Channel not found.",
                "domain": "youtube.playlist",
                "reason": "channelNotFound",
                "location": "channelId",
                "locationType": "parameter"
            }
        ]
    }

**Comment by tananga** [comment]
So I changed oauth token programatically which is very bad habit but it works. 
It looks like final "httpClient = await _googleSignIn.authenticatedClient();" returns token which is not accepted by YoutubeAPI.
Can anyone take a look on that ? Why the heel generated token witch all the youtube scopes is not valid ?

**Comment by tananga** [comment]
I see the first popup. And I can choose my gmail account. But when I try to load some private data from youtube I should see second popup to choose the youtube channel because I have multiple channels assign to my google acount but the second popup don't open and I have error 404 channel not found and thats very strange because when I used https://developers.google.com/people which is very similar to youtube api everything is working great

**Comment by tananga** [comment]
@kevmoo Can you take a look ?

**Comment by kevmoo** [comment]
@tananga – you need to make sure the service you're getting your token from with `authenticatedClient` has the proper access, too!

**Comment by tananga** [comment]
@kevmoo I dont understand, can you explain ?
