### ISSUE TITLE
[PubSub Api] How to create a StreamingPull that will continuously listen for messages?

### ISSUE THREAD

**Issue by orgesballa** [google/googleapis.dart#262]
I have an API that publishes messages to subscribers.
 
 In flutter, I have a subscriber and I need to pull messages from the API every time they are published. 
 
```
 String subscriptionName = 'projects/test/subscriptions/test-sub';
    pubSubClient.projects.subscriptions
        .pull(
            PullRequest.fromJson({
              "maxMessages": 1000,
            }),
            subscriptionName)
        .then((pullResponse) {
      if (pullResponse.receivedMessages != null &&
          pullResponse.receivedMessages.isNotEmpty) {
        List<String> ids = [];
        pullResponse.receivedMessages.forEach((element) {
          ids.add(element.ackId);
        });
        pubSubClient.projects.subscriptions.acknowledge(
            AcknowledgeRequest.fromJson({"ackIds": ids}), subscriptionName);
      }
    });
 ```
    
    This works but this is run only once. In the Google Cloud API, it says to use a StreamingPull to efficiently receive messages? 
    
    How can this be done in flutter and what other options are there?

**Comment by kevmoo** [comment]
Not exactly sure how to run with this. I'd suggest looking at https://cloud.google.com/pubsub/docs

**Comment by stevedj** [comment]
Hi @kevmoo, I am facing the same issue, 
base on the answer above, does it mean we have to use RPC to make the StreamingPull works?
I have tried to double-check the code, it seems it has not been implemented yet?
Please correct me if I am wrong, or any timeline when it will be implemented?

Thank you for your amazing support

**Comment by kevmoo** [comment]
Hey @stevedj – sadly, you are NOT able to do a "StreamingPull" with the REST API – which is what this is. 🤷

**Comment by stevedj** [comment]
Hi Kevin Moore, @kevmoo,

Good day, and thank you for your blazing fast reply,
I am a newbie in pubsub, and I understand that this is a REST API plugin, 
but I do have several questions if you don't mind answering them:

a. I use the pub-sub Service Account value to connect and fill the parameter like certificates and authority using [ChannelCredential](https://pub.dev/documentation/grpc/latest/grpc/ChannelCredentials-class.html), 
for the authority field, I fill it with auth_provider_x509_cert_url from the service account field
for the certificates I open the client_x509_cert_url link in the service account, and I found two keys in it, and I copied one of them as a string 

{
  "42723f3......": "-----BEGIN CERTIFICATE-----\n......ceUsYIAvKeFh\nhYeLWr......\n-----END CERTIFICATE-----\n",
  **"e76a5......": "-----BEGIN CERTIFICATE-----\n.......8BQqo7D5sJtPszUNWCYRqZDu7nLlaWMC3CieFHxfCq8=....\n-----END CERTIFICATE-----\n"**
}

and transform it to an array of int, using utf8encode, but It gives me an error 
Unhandled Exception: gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: HandshakeException: Handshake error in client (OS Error: 
        CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:354)), details: null, rawResponse: null)

Just wondering what value should we put in the ChannelCredentials class initiate connection?

b. Just clarifying as described in [gRPC architecture](https://grpc.io/docs/what-is-grpc/introduction/), to access PubSub, our stub (flutter client app) will directly connect to the pubsub gRPC server, and we don't need to create our own gRPC server?
Please correct me if I am wrong


That's all that I want to ask,

Warmest regards
Steve

**Comment by stevedj** [comment]
Hi Kevin Moore, @kevmoo,

I think I am able to make the connection work, by understanding CallOptions from this link,
https://gist.github.com/jonasfj/4d1dd980994cd923e045af79fe2fab4c

But, currently, I am having an issue 
Unhandled Exception: gRPC Error (code: 13, codeName: INTERNAL, message: A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0], details: [], rawResponse: null)

What I did was creating a subscription using the googleapis plugin and gcloud plugin,
then I am subscribing it using streamingpull

I have checked the error code from here
https://grpc.github.io/grpc/core/md_doc_statuscodes.html

But Ijust wondering what causing it?

Warmest Regards
Steve

**Comment by stevedj** [comment]
Hi Kevin Moore,

Good day!
I am able to make it work by using this sample code
https://gist.github.com/jonasfj/4d1dd980994cd923e045af79fe2fab4c

```
    final channel = ClientChannel("pubsub.googleapis.com",
        port: 443,
        options: ChannelOptions(
          credentials: ChannelCredentials.secure(),
        ));
    final stub = SubscriberClient(channel);
    request = streamingPullRequestController.stream;
    StreamingPullRequest pullRequest = new StreamingPullRequest(
      subscription: subscriptionPath,
      clientId: clientId,
    );
    streamingPullRequestController.add(pullRequest);
    stub
        .streamingPull(request, options: options)
        .asBroadcastStream()
        .listen((event) {
      print("event streamingPull");
      print(event);
    }).onError((handleError) {
      print("handleError");
      print(handleError);
    });
```

But I got this error while trying to "streamingPull" the stub :
handleError
gRPC Error (code: 13, codeName: INTERNAL, message: A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0], details: [], rawResponse: null)
(I have checked the error code but I still don't understand)

May I know if there is a solution for this?

Best Regards
Steve
