### ISSUE TITLE
@kevmoo Please don't close issues so fast, I still dont know how to solve my problem.

### ISSUE THREAD

**Issue by tananga** [google/googleapis.dart#264]
Hello.
Last time I created an issue because I cant get private data from YoutubeApi even with oauth2 token.
https://github.com/google/googleapis.dart/issues/261

This is very important for me. I cant create my dream app without it.
Can you guys tell me what's wrong ?

@kevmoo Told me that "you need to make sure the service you're getting your token from with authenticatedClient has the proper access, too!" But I still don't understand. I have oauth2 token. I have all scopes. What I need more ?

Btw. I found this and I love it: https://youtu.be/z4MsuZiEezY

Here is a code:

```dart
import 'package:extension_google_sign_in_as_googleapis_auth/extension_google_sign_in_as_googleapis_auth.dart'
    as auth;
import 'package:google_sign_in/google_sign_in.dart';
import 'package:googleapis/people/v1.dart';
import "package:googleapis/youtube/v3.dart";
import 'dart:async';
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Google Sign In',
      home: SignInDemo(),
    ),
  );
}

class SignInDemo extends StatefulWidget {
  @override
  State createState() => SignInDemoState();
}

class SignInDemoState extends State<SignInDemo> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Google Sign In'),
        ),
        body: ConstrainedBox(
          constraints: const BoxConstraints.expand(),
          child: _buildBody(),
        ));
  }

  Widget _buildBody() {
    return ElevatedButton(
      child: const Text('SIGN IN'),
      onPressed: _handleSignIn,
    );
  }

  Future<void> _handleSignIn() async {
    final _googleSignIn = new GoogleSignIn(
      scopes: [
        // PeopleServiceApi.contactsReadonlyScope,
        YouTubeApi.youtubepartnerScope,
        YouTubeApi.youtubeForceSslScope,
        YouTubeApi.youtubeScope,
        YouTubeApi.youtubeReadonlyScope,
        YouTubeApi.youtubeChannelMembershipsCreatorScope,
        YouTubeApi.youtubeScope,
        YouTubeApi.youtubepartnerChannelAuditScope,
      ],
    );
    await _googleSignIn.signOut();
    await _googleSignIn.signIn();

    final httpClient = await _googleSignIn.authenticatedClient();
    final YouTubeApi youtubeApi = YouTubeApi((httpClient)!);

    final response = await youtubeApi.playlists.list(
      ["snippet"],
      mine: true,
      maxResults: 25,
    );
    print(response.items!.length);
    print(response.items);
  }
}

```

With PeopleApi everything works fine and I can get my private contact list but youtube don't accept my token

**Comment by tananga** [comment]
![Screenshot 2021-07-07 at 23 27 30](https://user-images.githubusercontent.com/44244477/124831166-25052e00-df7b-11eb-8f23-1d31ebc132ba.png)

**Comment by tananga** [comment]
![Screenshot 2021-07-07 at 23 32 09](https://user-images.githubusercontent.com/44244477/124831568-b4aadc80-df7b-11eb-9a72-5f04e8550ae7.png)

**Comment by tananga** [comment]
![Screenshot 2021-07-07 at 23 33 30](https://user-images.githubusercontent.com/44244477/124831626-ca200680-df7b-11eb-957d-49dd1f3e6f88.png)

**Comment by tananga** [comment]
When I try to run it on browser Im getting Error: PlatformException(idpiframe_initialization_failed, Not a valid origin for the client: http://localhost:63569 has not been registered for client ID 348834361773-0n5e7ttu8hc1pb1apcg1eq3p1d7g59rb.apps.googleusercontent.com.

**Comment by kevmoo** [comment]
You need to run the app from the command line, likely. Just so you can
register the same URL – including the port!

**Comment by tananga** [comment]
So for example: flutter run -d chrome --web-port=1234 ? And I need to add this http://localhost:1234/#/ into credentials ?

**Comment by tananga** [comment]
Thank you @kevmoo  it works for web. Now I only need to check it in android

**Comment by tananga** [comment]
Now I want to do this step but for android:
<meta name="google-signin-client_id" content="YOUR_GOOGLE_SIGN_IN_OAUTH_CLIENT_ID.apps.googleusercontent.com">

**Comment by kevmoo** [comment]
https://flutter.dev/docs/development/data-and-backend/google-apis?utm_source=go-link&utm_medium=referral&utm_campaign=go-google-apis

**Comment by tananga** [comment]
I added something like this.
![Screenshot 2021-07-08 at 00 31 29](https://user-images.githubusercontent.com/44244477/124836898-14a58100-df84-11eb-9d9e-658d4797348e.png)
let me go forward and check if this soled my issue

**Comment by tananga** [comment]
When I run my flutter app on web with this command: flutter run -d chrome --web-port=1234 at first time it worked perfect. Then I closed it and execute the same command flutter run -d chrome --web-port=1234 onca again and now after click on sign in I see popup and spinner insider. Popup close very fast and  Youtube returns me DetailedApiRequestError(status: 404, message: Channel not found.) So its the same problem which I had on android

**Comment by tananga** [comment]
after "flutter clean" in the terminal my flutter app running on web runs great but only once. When I close the browser window and run my app second time "flutter run -d chrome --web-port=1234" once again popup's open and close very fast (Icant select account) and I get response DetailedApiRequestError(status: 404, message: Channel not found.)

**Comment by tananga** [comment]
And on android even after "flutter clean" I still cant select youtube account and I get DetailedApiRequestError(status: 404, message: Channel not found.)

**Comment by tananga** [comment]
@kevmoo found a bug In Google_sign_in package. I created an issue: https://github.com/flutter/flutter/issues/86049. 
I think that we can close this issue and wait for solution.
