### ISSUE TITLE
Google Text to Speech v1beta1 Client API is missing

### ISSUE THREAD

**Issue by bguan** [google/googleapis.dart#266]
I would like to incorporate the following version of Google speech to text API in my app.

https://cloud.google.com/text-to-speech/docs/reference/rest/v1beta1/text

I was able to find the v1 API in [googleapis](https://pub.dev/packages/googleapis) but the v1beta1 client is missing from [googleapis_beta](https://pub.dev/packages/googleapis_beta) package.

**Comment by kevmoo** [comment]
We've explicitly excluded v1beta1 because v1 is more current – it's "preferred".

Any reason you want the beta API?

**Comment by bguan** [comment]
i wanted to use the phoneme tag in SSML, i was under the impression it is a beta feature? 

this document seems to indicate that it is a beta feature. https://cloud.google.com/text-to-speech/docs/phonemes

I interpreted it to be not  yet fully supported in v1.  Am I wrong to assume that?  I did test it under v1 and it sort of works... but I am not sure if it is really supported in v1.

**Comment by kevmoo** [comment]
@bguan – we just expose what's given to us via the JSON descriptions. You'd have to look at their docs for options to ask questions about this.
