### ISSUE TITLE
[discoveryapis_generator] Null check operator used on a null value [feature request]

### ISSUE THREAD

**Issue by Greatcallie** [google/googleapis.dart#289]
This url (https://yourapp.appspot.com/_ah/api/discovery/v1/apis/) returns a json with kind of discovery#directoryList instead of discovery#restDescription and that breaks everything and returns error "Null check operator used on a null value".
After hours of brainstorming I solved it by picking the rest url from each of the api list in my json file and getting the json which is now of the kind discovery#restDescription. So I suggest the tool can be upgraded to handle this automatically.

**Comment by kevmoo** [comment]
The discovery generator is only lightly maintained for its core purpose. We're likely not going to crank on this.

**Comment by Greatcallie** [comment]
And Google doesn't want new developers to use app engine. Most of them
can't even build an api because there are no more documentations!

**Comment by kevmoo** [comment]
I'm happy to take a pull request for this feature if you think it's important. Just trying to set expectations.

**Comment by Greatcallie** [comment]
No I believe only experienced developers still use app engine and they can
take care of themselves. I will continue to use Datastore for as long as I
can. Google must not force Firestore on me. I will rather use Mongodb or
something else. I am grateful that this api generator was even built. It's
a lot better than the service generator for building ObjectiveC api for ios
and all the headaches... This is a win for Flutter!
