### ISSUE TITLE
Documentation link 404

### ISSUE THREAD

**Issue by bordunosp** [google/googleapis.dart#290]
Part: "Google OAuth2 API - oauth2.v2"
Link: "API details"

https://pub.dev/documentation/googleapis/5.0.0-dev/oauth2.v2/oauth2.v2-library.html

**Comment by kevmoo** [comment]
Looks like dartdoc timed out. 🤷 

![image](https://user-images.githubusercontent.com/17034/131230080-ac183d97-0f98-4935-bc84-363d3a12d414.png)

**Comment by kevmoo** [comment]
Check out the latest! https://pub.dev/documentation/googleapis/latest/oauth2.v2/oauth2.v2-library.html
