### ISSUE TITLE
Value's returning 'NULL_VALUE' for all fields as well as other data types

### ISSUE THREAD

**Issue by jimmyff** [google/googleapis.dart#291]
Previously if `Value.nullValue` was equal to `"NULL_VALUE"` then the `Value` was null, however since version 4.0.0 all my firestore documents field values have `nullValue == "NULL_VALUE"` in addition to their correct values such as a `integerValue` or `mapValue`

**Comment by kevmoo** [comment]
Could you give me more information, @jimmyff ?

Here's the source bug: https://github.com/google/googleapis.dart/issues/211

Here's the corresponding fix: https://github.com/google/googleapis.dart/commit/560d4b32db5fdd641d55f24209755022d6115414

**Comment by torbenkeller** [comment]
The commit didn't fix the issue. https://github.com/google/googleapis.dart/commit/560d4b32db5fdd641d55f24209755022d6115414#r56290820
