### ISSUE TITLE
Obtain Access Credentials Via User Consent - Desktop

### ISSUE THREAD

**Issue by MelbourneDeveloper** [google/googleapis.dart#292]
### Background
My Flutter app has a gRPC backend service hosted on Cloud Run. I need to authenticate the end-user with Google and send the bearer token with each gRPC call. The user will click the [Sign in with Google](https://developers.google.com/identity/branding-guidelines) button to log in. The user will log in and that will return the access credentials to the app (via the deep link I'm guessing). I've managed to achieve this with the `googleapis_auth` package despite it not quite being designed for this. I'm currently using the `obtainAccessCredentialsViaUserConsent` method. The client is Windows but this be necessary for other platforms including phones.

### Issue 
The problem is that `obtainAccessCredentialsViaUserConsent` requires the ClientId secret. That means that I cannot include this code in a production app because I'd be handing over the secret. 

### Solution
I would imagine the solution would involve requesting the consent Url from a backend call (where the secret can be stored securely and not be public) launching that Url and then capturing the access credentials via the deep link returned. 

### Existing Code 
```Dart
    final id = ClientId(
        "[ID]",
        "[SECRET]");
    final scopes = <String>['https://www.googleapis.com/auth/userinfo.email'];

    final client = http.Client();
    final credentials = await obtainAccessCredentialsViaUserConsent(
        id, scopes, client, _launchURL);
```

This works exactly as expected. I get the credentials and those credentials allow me to make authenticated calls to the gRPC service.

### Proposed Change
If the library does not already have such a call, I should be able to make a call that is something like `waitForCredentials()` that will await the consent screen sending the credentials to the app. If this exists already, please let me know. Otherwise, is there a possibility of adding such a feature in future?

**Comment by kevmoo** [comment]
> @kevmoo but for me it does not seem to be implemented

It's not!

https://developers.google.com/identity/protocols/oauth2/openid-connect#hd-param

Please file a separate issue for this, please!

**Comment by Y0ngg4n** [comment]
@kevmoo i will do.

**Comment by kevmoo** [comment]
@MelbourneDeveloper – could you please outline the new/changed APIs you want here? I'm not sure I completely follow your desired flow.

What would the client call? What would the server call? 

etc etc

**Comment by MelbourneDeveloper** [comment]
@kevmoo 

I'm not exactly sure how this works. What I understand is that the secret key plays some part in generating the `redirectionUri`. That's fine if the secret key sits on the server, but if it's exposed to the user, they get the secret key and it's not good. 

I'm going to spend some more time going through the code so I can figure out how the `redirectionUri` is generated and what role the secret key plays.

**Comment by kevmoo** [comment]
Send me a DM on twitter. Let's chat about this!

**Comment by kevmoo** [comment]
Specifically, you can send the clientId WITHOUT the secret

**Comment by MelbourneDeveloper** [comment]
I now believe that this is a non-issue. The code I posted above works fine on desktop and I believe it poses no security problem with a few caveats.

```Dart
    final id = ClientId(
        "[ID]",
        "[SECRET]");
    final scopes = <String>['https://www.googleapis.com/auth/userinfo.email'];

    final client = http.Client();
    final credentials = await obtainAccessCredentialsViaUserConsent(
        id, scopes, client, _launchURL);
```

**Background**
I thought that we should protect the `client_secret`. According to this article:

> The client_secret is a secret known only to the application and the authorization server. 

But, the [PKCE flow](https://www.oauth.com/oauth2-servers/pkce/) doesn't seem to require the `client_secret`  or makes it less important.

> The technique involves the client first creating a secret, and then using that secret again when exchanging the authorization code for an access token. This way if the code is intercepted, it will not be useful since the token request relies on the initial secret.

The [oAuth doco](https://www.oauth.com/oauth2-servers/single-page-apps/#authorization) says this of Single Page Apps (which are architecturally similar to native apps)

> Since the entire source is available to the browser, they cannot maintain the confidentiality of a client secret, so the secret is not used for these apps.

Several oAuth2 endpoints I came across dispense with client_secret altogether in the PKCE flow. Oddly, the Google endpoint does require it, and that's why it's necessary to include the `client_secret` in your Flutter app. 

According to [Google](https://googleapis.github.io/google-api-python-client/docs/oauth-installed.html#overview):

> The client ID and client secret obtained from the API Console are embedded in the source code of your application. In this context, the client secret is obviously not treated as a secret.

This renders the `client_secret` kind of pointless but from my understanding should be safe to add to your app where it is publicly visible **as long as**: you do not share the Client Id and Client Secret with other apps that require them. **If you use other server-side workflows, you must create separate client ids and secrets, and you must never hand those secrets over in your apps**.

So, it appears to me that it is safe to put your `client_secret` inside the app.

@kevmoo please feel free to close this issue if what I've said matches what you understand.

**Comment by MelbourneDeveloper** [comment]
@Y0ngg4n see above ^^^

**Comment by kevmoo** [comment]
@MelbourneDeveloper – turns out I WANT this fixed – to enable server apps! No worries.

**Comment by ascott18** [comment]
I would love to see this done. In addition to wanting to perform the code exchange on my server rather than on the client, I have an additional use case for it - the URL for the token exchange that is hardcoded into this library, `https://accounts.google.com/o/oauth2/token` does not return a "picture" claim on the id_token, but `https://oauth2.googleapis.com/token` does return a "picture" claim. Because this URL is hardcoded, there's no way to customize it.

So, it would be nice if `_obtainAccessCredentialsUsingCode` was overridable so we can perform whatever customization we need in the code exchange.

**Comment by kevmoo** [comment]
> I would love to see this done. In addition to wanting to perform the code exchange on my server rather than on the client, I have an additional use case for it - the URL for the token exchange that is hardcoded into this library, `https://accounts.google.com/o/oauth2/token` does not return a "picture" claim on the id_token, but `https://oauth2.googleapis.com/token` does return a "picture" claim. Because this URL is hardcoded, there's no way to customize it.
> 
> So, it would be nice if `_obtainAccessCredentialsUsingCode` was overridable so we can perform whatever customization we need in the code exchange.

This would be a separate request. Please file another issue, @ascott18 – to add on here. You could also use https://pub.dev/documentation/googleapis/latest/oauth2.v2/UserinfoV2MeResource/get.html

**Comment by kevmoo** [comment]
After talking to @MelbourneDeveloper – I think this can be closed out.

**Comment by nickmeinhold** [comment]
@kevmoo sorry to butt in, can I ask - was @MelbourneDeveloper's [description above](https://github.com/google/googleapis.dart/issues/292#issuecomment-945021024) matching your understanding?  I found it extremely helpful (thanks!), having puzzled over the same question of an "obviously not treated as a secret" client_secret more than once.  Perhaps this would be a helpful addition to the documentation?  Happy to PR if so and no-one else wants to do it.  Thanks!

**Comment by kevmoo** [comment]
> @kevmoo sorry to butt in, can I ask - was @MelbourneDeveloper's [description above](https://github.com/google/googleapis.dart/issues/292#issuecomment-945021024) matching your understanding? I found it extremely helpful (thanks!), having puzzled over the same question of an "obviously not treated as a secret" client_secret more than once. Perhaps this would be a helpful addition to the documentation? Happy to PR if so and no-one else wants to do it. Thanks!

That DOES match my understanding. A PR to clarify this code would be welcome!
