### ISSUE TITLE
Broken documentation link for Google Drive API

### ISSUE THREAD

**Issue by flutternoob** [google/googleapis.dart#293]
The API documentation links for both Google Drive v2 and v3 are broken.

**Comment by kevmoo** [comment]
WHere are you looking?

**Comment by KKStudios** [comment]
I'm also looking for the documentation.

Under https://flutter.dev/docs/development/data-and-backend/google-apis it says: 

The documentation for package:googleapis lists each API as a separate Dart library – in a name.version format. Let’s look at youtube.v3 as an example. package:googleapis lists leads to https://pub.dev/documentation/googleapis/latest/ which is missing.

Under https://pub.dev/packages/googleapis

scrolling down to 
Drive API - drive.v3
Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.

Documentation
API details -> leads to https://pub.dev/documentation/googleapis/latest/drive.v3/drive.v3-library.html which is missing

Hope this helps.

**Comment by kevmoo** [comment]
Yup. Crap. Doc generation is timing out here.
