### ISSUE TITLE
Refused to set unsafe header "user-agent", "content-length"

### ISSUE THREAD

**Issue by ditman** [google/googleapis.dart#298]
(**partial** regression of #73)

Doing some recent testing with the `googleapis` package [here](https://github.com/flutter/flutter/issues/89301), I noticed the following errors in the JS console of the browser:

```
Refused to set unsafe header "user-agent"
forEach	@	linked_hash_map.dart:21
send	@	browser_client.dart:52

[...]

Refused to set unsafe header "user-agent"
forEach	@	linked_hash_map.dart:21
send	@	browser_client.dart:52
```

It seems that this code is no longer working as expected:

https://github.com/google/googleapis.dart/blob/516dbc59b675d0b15a214e06924876a9939f653c/discoveryapis_commons/lib/src/api_requester.dart#L318-L324

Because `_forbiddenHeaders` seems to always be the empty Set.

**Comment by kevmoo** [comment]
I wonder if the compiler feature that sets `dart.library.html` changed.

**Comment by ditman** [comment]
This only happens when compiling in `debug` mode:

`flutter run -d chrome`

But not when compiling in `release` mode:

`flutter run -d chrome --release` (or `flutter build web`)

**Comment by ditman** [comment]
The fix for this has landed in flutter `master` already.
