### ISSUE TITLE
Google Drive API Access via URL

### ISSUE THREAD

**Issue by M-A-D-A-R-A** [google/googleapis.dart#307]
Is it Possible that we don't need any ClientID for access the API , for Eg we Provide a public URL (Read and Write access to everyone) of a Drive URL and and the user don't have to login via Google Auth /API KEY, he can just use that URL, because the URL is public so anyone can have access to edit it.

If it is possible then. how?

Thanks

**Comment by kevmoo** [comment]
We just expose the underlying API.

You'll have to dig in at https://developers.google.com/drive/ to figure your your question.
