### ISSUE TITLE
Hosted Domain Restriction to Oauth2

### ISSUE THREAD

**Issue by Y0ngg4n** [google/googleapis.dart#314]
As discussed in #292  i am trying to use the [googleapis_auth](https://pub.dev/packages/googleapis_auth) package and trying this code from the docs: 

```
import "package:http/http.dart" as http;
import "package:googleapis_auth/auth_io.dart";

...

var id = ClientId("....apps.googleusercontent.com", "...");
var scopes = [...];

var client = http.Client();
obtainAccessCredentialsViaUserConsent(id, scopes, client, prompt)
    .then((AccessCredentials credentials) {
  // Access credentials are available in [credentials].
  // ...
  client.close();
});

void prompt(String url) {
  print("Please go to the following URL and grant access:");
  print("  => $url");
  print("");
}
```

But i want to restrict the logins to just @foobar.com domains so only users with a @foobar.com email can login.
I have found that this can be do via the `hosted_domain` oder `hd` parameter via [this Stackoverflow entry](https://stackoverflow.com/questions/10858813/restrict-login-email-with-google-oauth2-0-to-specific-domain-name).
But i dont know how i can use this in a Dart/Flutter Project.

**Comment by kevmoo** [comment]
Got it working! https://github.com/google/googleapis.dart/pull/323

**Comment by Y0ngg4n** [comment]
@kevmoo works perfectly 😊👍

**Comment by Y0ngg4n** [comment]
@kevmoo found an issue:
when using web version `import "package:googleapis_auth/auth_browser.dart"`. I cant use `obtainAccessCredentialsViaUserConsent` with hosted domains.

**Comment by kevmoo** [comment]
@Y0ngg4n – would you open a seperate issue? Are you missing an API? What error are you getting, etc etc

**Comment by Y0ngg4n** [comment]
@kevmoo https://github.com/google/googleapis.dart/issues/344
