### ISSUE TITLE
Hosted Domains for Web Version does not work

### ISSUE THREAD

**Issue by Y0ngg4n** [google/googleapis.dart#344]
@kevmoo 
When using web version import "package:googleapis_auth/auth_browser.dart". I cant use obtainAccessCredentialsViaUserConsent with hosted domains.

Also i get this error even when i registered url in the auth panel:

```
Failed to get user consent: idpiframe_initialization_failed. Not a valid origin for the client: https://volt.oblivioncoding.pro has not been registered for client ID 730828446100-ijqtpdsc8nljjh7fdamuefbe2b21etha.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and register this origin for your project's client ID.
```

**Comment by kevmoo** [comment]
Have you done the registration as asked in the error message?

**Comment by Y0ngg4n** [comment]
@kevmo
yes 
![image](https://user-images.githubusercontent.com/30302975/140199164-6360c975-d017-4986-8e5a-19a21dc9fcc2.png)

**Comment by kevmoo** [comment]
@Y0ngg4n – does that change the error you're getting?

**Comment by Y0ngg4n** [comment]
i allready did that before and the error appears again

**Comment by kevmoo** [comment]
This is just a wrapper over existing HTTP/Browser APIs.

Do you have any indication that it's more likely the code in this package is wrong – or your configuration is wrong?

**Comment by Y0ngg4n** [comment]
@kevmoo the error is gone. I now just want to make hosted domains working. But i dont know where to place the hosed domains parameter

**Comment by kevmoo** [comment]
I think we need to work here: https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeparams_callback

**Comment by kevmoo** [comment]
@Y0ngg4n – any way you could try out the code at https://github.com/google/googleapis.dart/tree/i344_hosted_domains_web to see if this addresses your needs?

**Comment by Y0ngg4n** [comment]
@kevmoo i can try it out the next days.

**Comment by kevmoo** [comment]
@Y0ngg4n  This is landed at master now. I'd love you to validate it before I publish!

**Comment by Y0ngg4n** [comment]
@kevmoo i will check it out :)

**Comment by Y0ngg4n** [comment]
@kevmoo seems to work :)
