### ISSUE TITLE
GoogleApis Null Data

### ISSUE THREAD

**Issue by SercanKaya0** [google/googleapis.dart#347]
Hello, the data is coming, but when I want to show the data on the screen, it is null. What is the reason?
<img width="1552" alt="Ekran Resmi 2021-11-06 18 26 30" src="https://user-images.githubusercontent.com/60138522/140614926-6cb72e13-5c7c-4e5e-a198-adc17f77c04a.png">

**Comment by kevmoo** [comment]
You'll have to put a debugger on it and look at the response. I cannot see from this whether it's a API issue or if you're calling it wrong...

**Comment by sanderveenman** [comment]
Not sure if its the same issue, but when i try to retrieve the description , date created, or size it all returns zero. In the google drive webconsole, the description does get set when i create the file. It somehow doesnt get retrrieved 

` Future<void> _listGoogleDriveFiles() async {
    print('fetching');
    var client = GoogleHttpClient(await _currentUser!.authHeaders);
    var drive = ga.DriveApi(client);

   // drive.files.list(spaces: 'appDataFolder').then((value) {
      drive.files.list().then((value) {
      setState(() {
        driveItemslist = value;
      });
       print(driveItemslist!.files!.length);
      for (var i = 0; i < driveItemslist!.files!.length; i++) {
        print(driveItemslist!.files![i]);
        print("Name: ${driveItemslist!.files![i].name} File Size:${driveItemslist!.files![i].size} file Description: ${driveItemslist!.files![i].description}");
      }
    });
  }`

the resulting printout of size and description are null

**Comment by kevmoo** [comment]
You might not be requesting the right things.

Could you include the output of `print(value.toJson())`?

**Comment by sanderveenman** [comment]
hi, thx for your reply. 
print(value.toJson()) returns :
I/flutter (27566): {files: [{id: 1sp6UYW5_hJn2ERzgS1RnkrxtU4sli9Fg, kind: drive#file, mimeType: application/octet-stream, name: places.db}], incompleteSearch: false, kind: drive#fileList}
