### ISSUE TITLE
Firestore api ArrayValue with length 0 has null instead of empty list as .values field.

### ISSUE THREAD

**Issue by whesse** [google/googleapis.dart#349]
A non-empty Firestore Value of type ArrayValue has a .values field containing List<Value>.
An empty ArrayValue has a .values field containing null, rather that one containing an empty list.
This applies to ArrayValue objects created by the API, when returning values from a getDocument call, for example.

This happens because the JSON returned by the Firestore REST API sends a map for array_value with no value field, rather than a value field with an empty list. This is probably because protocol buffers, that underlie the Google APIs, represent an empty repeated field as a missing field.

The curated Google APIs avoid this. For example, the Javascript API handles this, and creates a JS object with an empty list, instead of null:
https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/lite-api/user_data_writer.ts#L113

If it is impossible to generate an API that fixes this, because it is generated code from the discovery document, is it possible to improve the documentation for the ArrayValue class, so that it says that the values field is null if the array is empty?

Right now, it just says:
values ↔ List<Value>?
Values in the array.

**Comment by kevmoo** [comment]
Sadly, this is not easy. The only tweaks we do to existing APIs is to add patches to the JSON.

Doing one-off API hacks is really tough to maintain and might mess with the semantics of the API.

If feel your pain here, though.
