### ISSUE TITLE
Ponder ways to make uploading `Media` class "observable"

### ISSUE THREAD

**Issue by KKStudios** [google/googleapis.dart#352]
Hi, 

probably my question is totally easy but I searched the whole day and couln't find any answer here in the Issues, or in the Documentation.

I'm looking for a way to hook into the Upload process to get some kind of upload progress with the resumable Upload.
Since it uploads the file in chunks, there should be some kind of possibility getting notified when one chunk is uploaded.

I've tried to subscribe to the Stream of the media file, but then the upload takes infinite time. Also I'm assuming it is just reading the Media there, so does not say anything about the upload itself right?

Also I've tried to make my own http Client class that listens to the response and notifies any subscribers but then again, the Drive api listenes to that aswell and I'm getting an error that the StreamedResponse has already been listened to.

So does somebody has any suggestions? Or might this even be a feature request to add some kind of callback or stream to listen to whenever a chunk of data has been successfully uploaded?

```dart
import 'dart:async';
import 'dart:developer';
import 'dart:io' as io;
import 'package:flutter/material.dart';
import 'package:googleapis/drive/v3.dart';
import 'package:http/http.dart' as http;
import 'package:googleapis_auth/auth_io.dart';


Future<void> testMethod() async{

  io.File file = io.File("testFile_Upload.txt");

  log("getting auth");
  GoogleAuthenticator auth = GoogleAuthenticator();
  AccessCredentials creds = await auth.authenticate();
  log("creds are there");
  http.Client baseClient = http.Client();
  http.Client authClient = authenticatedClient(baseClient, creds);

  DriveApi api = DriveApi(authClient);

  File fileMeta = File(name: "testFile_Upload.txt", parents: ["appDataFolder"]);

  Media media = Media(file.openRead(), await file.length());

  log("starting upload");
  Future<File> resultFuture = api.files.create(fileMeta, uploadMedia: media, uploadOptions: UploadOptions.resumable);

  File result = await resultFuture;
  log("result: " + result.id.toString() + " / " + result.name!);

  authClient.close();
  baseClient.close();
  log("Done");
}
```

**Comment by kevmoo** [comment]
You might get away with wrapping the `file.openRead()` call. That's likely the easiest thing to do here!

**Comment by KKStudios** [comment]
@kevmoo It is and it's literally the elephant in the room. Thank you! Works like charm.

**Comment by bawantha** [comment]
How to do that?
