### ISSUE TITLE
Issue during big file creation

### ISSUE THREAD

**Issue by GSirma** [google/googleapis.dart#366]
Hello! I'm struggling with two issues those days with uploading only files over 60MB to drive through googleapis package (v0.56.1 and v1.0.0)

```dart
Future<drive.File> uploadFileToDrive(File file, String folderId) async {
    var _completer = new Completer<drive.File>();

    await getAuthClient();

    final reader = new FileReader();
    reader.onLoad.listen((e) async{
      try {
        var length = 0;
        var bodyController = StreamController<List<int>>();
        if (reader.result != null) {
          bodyController.add(reader.result);
          length = (reader.result as List<int>).length;
        }else {
          throw Exception('Can\'t read file!');
        }
        bodyController.close();

        (await _getDriveApi()).files.create(drive.File.fromJson({'mimeType': file.type, 'name': file.name, 'parents': [folderId]}), uploadMedia: drive.Media(bodyController.stream, length), uploadOptions: length > 1000000 ? drive.UploadOptions.Resumable : drive.UploadOptions.Default)
            .then((respFile) async{
              await publicPermissionFile(respFile.id);

              _completer.complete(respFile);
            })
            .catchError((e) => _completer.completeError(e));
      } catch (e) {
        window.console.log(e);
        _completer.completeError(e);
      }
    });

    reader.readAsArrayBuffer(file);

    return _completer.future;
  }
```

Issues:
1) Fail after first call to Drive API (Chrome browser issue only)
![image](https://user-images.githubusercontent.com/95858788/145395510-8224f9c1-76d5-44d5-868a-b0b54b242c37.png)

2) If I try the same operation with other browser it's not failing and sometimes upload successfully the same file which I'm trying many times. Drive API call timeout without any error not sure why this happen.
![image](https://user-images.githubusercontent.com/95858788/145395983-a50b4b15-c1ea-4f35-af7c-9a169ea1a12f.png)

I'm gonna repeat myself the issues above happen only in case when file is over 60MB. I'm not struggling with files with small size. I tried with different file types. During my tests I had 2-3 successfully file uploading and more that 8 unsuccessfully.

Thank you in advance!

**Comment by kevmoo** [comment]
Here you go https://github.com/google/googleapis.dart/pull/367/files#diff-ab0dc1da695f06972b9cd700510c5a82c7d27749e2dc9670fd2d40aab9bb6953

Will land this in the repo. This should be easier, but at least this code will get you going!

**Comment by GSirma** [comment]
Thanks that help me a lot!
btw. That also help me with integration of upload progression status bar!
