### ISSUE TITLE
Google Drive v3 API is missing `Files` class

### ISSUE THREAD

**Issue by RichardJECooke** [google/googleapis.dart#369]
According to the Google Drive documentation, file upload is achieved using `files.create()` - https://developers.google.com/drive/api/v3/reference/files/create.

But this googleapis Dart package doesn't have the `files` class (nor does the `file` class have a `create` method). - https://pub.dev/documentation/googleapis/latest/drive.v3/DriveApi-class.html

Has this functionality not been implemented yet? Or is there some other way of uploading files that is not documented anywhere?

Thanks.

**Comment by goranj** [comment]
Try the FilesResource class - https://pub.dev/documentation/googleapis/latest/drive.v3/FilesResource-class.html

**Comment by RichardJECooke** [comment]
> Try the FilesResource class - https://pub.dev/documentation/googleapis/latest/drive.v3/FilesResource-class.html

Thank you! How did you know this is the class to use? I don't see how the names in this package correspond to the names in Google Drive API? I can't see this documented.

Secondly, the create method here takes a `File` object. But I'm on Flutter for web (and not using local files anyway). Is there any way to create a file in memory, rather than on disk, to upload?

**Comment by goranj** [comment]
For the most part I use Dart and googleapis for backend jobs related to Google Workspace. So I’m not in a position to answer your Flutter questions. Maybe SO can help?

**Comment by RichardJECooke** [comment]
Thanks, yeah, I've asked there too but no one knows so far. I was hoping at least to understand how this library is documented.

**Comment by goranj** [comment]
Flutter aside, I think you can upload any stream of bytes you create:

https://dart.dev/articles/libraries/creating-streams

**Comment by kevmoo** [comment]
https://github.com/google/googleapis.dart/blob/61bf3528141259d850b5d38e054aec4ac93a8436/test_integration/web/drive_demo.dart#L56-L60

There *is* a File class in the Drive API. Just have to be careful when importing!

**Comment by RichardJECooke** [comment]
> https://github.com/google/googleapis.dart/blob/61bf3528141259d850b5d38e054aec4ac93a8436/test_integration/web/drive_demo.dart#L56-L60
> 
> There _is_ a File class in the Drive API. Just have to be careful when importing!

Sorry, are  you saying I should use File instead of FilesResource? Careful importing what?

**Comment by kevmoo** [comment]
I'm guessing you're importing `dart:io` and using that `File` class – https://api.dart.dev/stable/2.16.1/dart-io/File-class.html

You *need* to be using the `File` class from the drive API - https://pub.dev/documentation/googleapis/latest/drive.v3/File-class.html
