### ISSUE TITLE
Writing Calorie data to Google Fit using googleapis package (Fitness API) with Flutter 

### ISSUE THREAD

**Issue by iamadeeb** [google/googleapis.dart#370]
Is there a way to write calorie as a Session to Google Fit using Fitness API with Flutter? I tried Google API package for that but the documentation is for native android app and not Flutter. Is there an example for that in Flutter?

**Comment by kevmoo** [comment]
We only have wrappers around the existing API.

Look here https://developers.google.com/fit/scenarios/add-nutrition-data#rest or similar

**Comment by iamadeeb** [comment]
I already checked all documentation but it's not very clear how to add data to Google Fit. For example after creating a data source and adding data points to it, I couldn't find a way in Flutter to add the datasource to a session in Google Fit app.

**Comment by kevmoo** [comment]
Sadly, I don't know either. We just expose the APIs as-is!

**Comment by iamadeeb** [comment]
Ok, thanks
