### ISSUE TITLE
firebaseremoteconfig API is missing

### ISSUE THREAD

**Issue by kevmoo** [google/googleapis.dart#382]
Responding to a couple of one-off messages.

The API endpoint is documented here: https://firebase.google.com/docs/reference/remote-config/rest

But for some reason it's no longer in: https://discovery.googleapis.com/discovery/v1/apis

Not sure why. I'll need to investigate.

**Comment by shilintfu** [comment]
It seems that the discovery of remote-config is available at here https://firebaseremoteconfig.googleapis.com/$discovery/rest?version=v1

Not sure if this is an unexpected url location for the remote config rest api

**Comment by kevmoo** [comment]
@shilintfu – that's fine. It's that the full API list (https://discovery.googleapis.com/discovery/v1/apis) no longer has that API. Weird.

I may be able to work around it, though.

**Comment by shilintfu** [comment]
@kevmoo Sounds good! Ideally, it will be great If the team managing the discovery.googleapis.com can review and help adding the remote config api to the list.

**Comment by kevmoo** [comment]
I agree!

**Comment by shilintfu** [comment]
Perfect! thanks

**Comment by kevmoo** [comment]
Shipped in v8.1.0

**Comment by shilintfu** [comment]
@kevmoo fantastic!

**Comment by shilintfu** [comment]
@kevmoo The support of remote config rest api is very helpful for the firebase remote config template integration and management. However, I think there are a few areas that may have room for enhancements.

1. **getRemoteConfig** should return "_Get a project's Remote Config template and associated **ETag header**_" according to the api documentation but it seems that the Etag header required for updateRemoteConfig is not accessible in v8.1.0
2. The api also states that the **updateRemoteConfig** should "_Pass the ETag returned by GetRemoteConfig as an 'If-Match' header to ensure the last seen Remote Config template ..._". There are two items observed for you/your team to review
    - Etag access issue as described in item 1 above
    - pass extra request header (e.g., 'If-Match' header) to updateRemoteConfig is not intuitive using the http client returned by clientViaServiceAccount.

Thoughts? 
Thanks

**Comment by kevmoo** [comment]
@shilintfu – sadly, these APIs are 100% auto-generated. There is no easy way to fix these without fixing the upstream definitions. I can try to ask around a bit, but I cannot make promises.

**Comment by shilintfu** [comment]
@kevmoo Understood! I should be able to workaround these limitations. The support of remote config template rest apis helped us a lot already. Thanks
