### ISSUE TITLE
Sharing file driver for anyone 

### ISSUE THREAD

**Issue by nguyendangkhoi** [google/googleapis.dart#387]
when I successfully upload the file, the permission cannot be set, is there any solution?

**Comment by kevmoo** [comment]
You'll have to use the docs here: https://developers.google.com/drive/

**Comment by nguyendangkhoi** [comment]
I'm talking about how to make the uploaded file have the share for anyone attribute,  Does this library support it?
ga.File fileToUpload = ga.File();
fileToUpload.shared = true; 
await drive.files.create(fileToUpload....);

**Comment by kevmoo** [comment]
These APIs are just generated from shared definitions. The best I can do is point you to the docs at https://developers.google.com/drive/ and figure things out there. I have no special knowledge of these APIs 🤷
