### ISSUE TITLE
How to use clientViaApplicationDefaultCredentials on Web? 

### ISSUE THREAD

**Issue by Wizzel1** [google/googleapis.dart#389]
I am trying to setup the SecretmanagerApi for my WebApp like this 

```dart
      final AutoRefreshingAuthClient client =
          await clientViaApplicationDefaultCredentials(
        scopes: [FirestoreApi.cloudPlatformScope],
      );
```

but I am getting an Error `Unsupported operation: Platform._environment`

I suppose this is because `auth_io` uses `dart:io`. So is there any chance to make this work? 

If not, what alternative should I use?

**Comment by kevmoo** [comment]
You cannot. You have to use the `auth_browser` library.

default credentials is 100% for server/desktop usage!

**Comment by kevmoo** [comment]
https://pub.dev/documentation/googleapis_auth/latest/auth_browser/auth_browser-library.html

These are the things you can use!
