### ISSUE TITLE
Invalid request / problem with redirect_uri

### ISSUE THREAD

**Issue by galvin59** [google/googleapis.dart#390]
Hi,

My iOS app suddenly stopped working a few days ago
Google Auth is retuning a 400 error (invalid_request), complaining about safety and redirect_url value (which is set to localhost on a random port, not even sure I have set that somewhere ...)
After a google search, it looks like it might be related to recent changes made by google on oauth : 
https://stackoverflow.com/questions/71318804/google-oauth-2-0-failing-with-error-400-invalid-request-for-some-client-id-but
Does anyone has a similar problem ?

Julien

**Comment by tomoyuki28jp** [comment]
Facing the same issue on macOS :(

**Comment by SungHyun22** [comment]
any update here????

**Comment by kevmoo** [comment]
Which package are you using for sign-in?

**Comment by kevmoo** [comment]
Is this happening with authentication or login? If you're on iOS are you using https://pub.dev/packages/google_sign_in

**Comment by galvin59** [comment]
Hi
I am using googleapis_auth package. The problem occurs on iOS (didn't try on Android)
Thanks !
Julien

**Comment by kevmoo** [comment]
For a web app or Flutter mobile?

**Comment by galvin59** [comment]
I use it in a Flutter mobile app
