### ISSUE TITLE
ListServicesResponse.fromJson failes with 'type '_GrowableList<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'

### ISSUE THREAD

**Issue by mark-at-pieces** [google/googleapis.dart#397]
hello:) 

I've been playing around with the cloud run api and strong typing my responses with these awesome classes!!  I ran into a little issue. heres some details down below please let me know if I can offer anymore details. Also thank you so much this is an awesome Library!! Another couple key details, the request is a successful and I'm getting a _GrowableList that I'm able to iterate over and convert to Service classes.

here's the request:
`
ProcessResult created = await Process.run(
  'gcloud',
  ['run', 'services', 'list', '--project=$project', '--format=json'],
  runInShell: true,
);
`

here's the deserialization: (that throws '_GrowableList<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>')
`
ListServicesResponse.fromJson(json.decode(created.stdout.toString()));
`

flutter version:
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (6 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2

heres the package version I'm using:
googleapis: ^7.0.0

**Comment by kevmoo** [comment]
The simple version is that `created.stdout` seem to be a `List` in JSON, but `ListServicesResponse` expects a `Map`.

Maybe you need https://pub.dev/documentation/googleapis/latest/run.v2/GoogleCloudRunOpV2ListServicesResponse-class.html ?

**Comment by mark-at-pieces** [comment]
hmm this https://pub.dev/documentation/googleapis/latest/run.v2/GoogleCloudRunOpV2ListServicesResponse/GoogleCloudRunOpV2ListServicesResponse.fromJson.html looks like it also takes in a map, but lemme give it a try

**Comment by mark-at-pieces** [comment]
primo works great! thank you! your a beast!
