### ISSUE TITLE
publish package:_discoveryapis_commons?

### ISSUE THREAD

**Issue by devoncarew** [google/googleapis.dart#404]
It would be useful to publish package:_discoveryapis_commons - that would capture a commit which updates the pubspec repository field from pointing to the root of the repo to pointing at the full monorepo path (https://github.com/google/googleapis.dart/tree/master/discoveryapis_commons).

**Comment by kevmoo** [comment]
Uh...we could.

**Comment by kevmoo** [comment]
Done! v1.0.3

**Comment by devoncarew** [comment]
Thanks!
