### ISSUE TITLE
Call Google Play Developer API from Flutter

### ISSUE THREAD

**Issue by blue492** [google/googleapis.dart#413]
I followed  [Google Play Developer API setup documentation][1] to connect my Flutter app to Google API. 

The app in Google play console is now connected to the project in Google Cloud Platform, so my question how Call Google Play Developer API from Flutter app and get the app details like published app version.

I didn't find any valuable documentation about calls between Flutter app and Google play API. I didn't have any information about Google API. I want to see if the connection is correct and how to get response from the API.

How to use Googleapis package to get the app details like published app version?
Thanks for help

  [1]: https://developers.google.com/android-publisher/getting_started

**Comment by kevmoo** [comment]
These APIs are generated. We don't know anything specific other than what the docs point to.

See https://pub.dev/documentation/googleapis/latest/androidpublisher.v3/androidpublisher.v3-library.html

**Comment by blue492** [comment]
> These APIs are generated. We don't know anything specific other than what the docs point to.
> 
> See https://pub.dev/documentation/googleapis/latest/androidpublisher.v3/androidpublisher.v3-library.html

Thanks for your reply, I wonder how to use Google Play Android Developer API in Googleapis package from dart  to get the app details like published app version, is there any valuable documentation?

**Comment by kevmoo** [comment]
>  is there any valuable documentation?

🤷
