### ISSUE TITLE
authenticatedClient() is missing on the instance of GoogleSignIn()

### ISSUE THREAD

**Issue by berryart** [google/googleapis.dart#432]
Following this tutorial: https://youtu.be/z4MsuZiEezY?t=251 I don't have the `authenticatedClient()` method on the `GoogleSignIn()` instance. Is this the right sequence of creating the instance and accessing the method?
```
GoogleSignIn  gsi = GoogleSignIn(
      clientId: "XXX",
      scopes: [YouTubeApi.youtubeReadonlyScope]
 );

gsi.signIn();

gsi.onCurrentUserChanged.listen((account) async {
  setState(() {
    _account = account;
  });

  if (_account != null) {
    final client = await gsi.authenticatedClient() // <- don't have this method on the gsi instance!
    final yapi = YouTubeApi(client);                      // <- as a consequence cannot create a YouTubeApi instance
  }
});

**Comment by mskmx** [comment]
You need add in your pubspec.yaml this extension:
[https://pub.dev/packages/extension_google_sign_in_as_googleapis_auth](https://pub.dev/packages/extension_google_sign_in_as_googleapis_auth)
And import in your file/class
`import 'package:extension_google_sign_in_as_googleapis_auth/extension_google_sign_in_as_googleapis_auth.dart';`

**Comment by kevmoo** [comment]
What @mskmx said!
