### ISSUE TITLE
Add Cloud Bigtable Data API?

### ISSUE THREAD

**Issue by tlv-finch** [google/googleapis.dart#435]
Hello! Would it be possible to add the [Bigtable Data API](https://cloud.google.com/bigtable/docs/reference/data/rpc) to this repo? I see that the Bigtable Admin API is [included](https://pub.dev/documentation/googleapis/latest/bigtableadmin.v2/bigtableadmin.v2-library.html), but as far as I can tell it seems to have no overlap with the Data API. Thanks!

**Comment by kevmoo** [comment]
The only APIs exposed here are the ones defined in https://discovery.googleapis.com/discovery/v1/apis – which (as you mention) include the admin API.

The RPC API is likely a gRPC API, which this package does not support, sadly.

**Comment by tlv-finch** [comment]
In case anyone else is wondering about this (or similar re: how to use a gRPC API in Dart), I was able to find this official example ([permalink](https://github.com/grpc/grpc-dart/tree/94b71a3e1cbfae366ead2d67f1b30fd03b8d4ee2/example/googleapis)) after (quite) some searching.

**Comment by kevmoo** [comment]
The only APIs exposed here are the ones defined in
https://discovery.googleapis.com/discovery/v1/apis – which (as you mention)
include the admin API.

The RPC API is likely a gRPC API, which this package does not support,
sadly.
