### ISSUE TITLE
No method to get bigquery.v2 QueryResponse in JSON format.

### ISSUE THREAD

**Issue by aalokdosii** [google/googleapis.dart#439]
bigquery.v2 does not have any method to get **QueryResponse in JSON format.** 

existing toJson() method does not covert rows data in JSON format. It returns array of Instance of 'TableRow'

Look at the following response, which is also not a valid JSON format:

`{cacheHit: true, jobComplete: true, jobReference: Instance of 'JobReference', kind: bigquery#queryResponse, rows: [Instance of 'TableRow', Instance of 'TableRow', Instance of 'TableRow'], schema: Instance of 'TableSchema', totalBytesProcessed: 0, totalRows: 3}`

**Comment by kevmoo** [comment]
You need to pass the results through `encodeJson` from `dart:convert` – then `jsonDecode` for the result.. It's likely a convention we need to move beyond, but it was meant to allow a lazy JSON encoding.

**Comment by aalokdosii** [comment]
Thanks Kevin! I still have a question. is possible to get query results in JSON similar to what we get in BQ console.
![image](https://user-images.githubusercontent.com/90391540/188792595-674d2930-3883-4a05-b960-630345ab5f4f.png)

**Comment by kevmoo** [comment]
@aalokdosii – I don't know. We just expose the API we are given. You'll have to look at the BigQuery docs!
