### ISSUE TITLE
How to call DetectIntents (Dialogflow V2) from Flutter(Dart).

### ISSUE THREAD

**Issue by mukutmani** [google/googleapis.dart#45]
Please help me to write request/response from flutter to dialalog.my below code giving error. 404.
Please help me to run these code or any modification need please help me on this.

[+1949 ms] E/flutter (10462): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[        ] E/flutter (10462): DetailedApiRequestError(status: 404, message: No error details. HTTP status was: 404.)

final scopes = ['https://www.googleapis.com/auth/cloud-platform'];
    final authenticatedHttpClient = await clientViaServiceAccount(accountCredentials, scopes);
    final df = new DialogflowApi(authenticatedHttpClient);
    final session ='https://dialogflow.googleapis.com/v2/projects/chatbot-d5783/agent';
    //final session = 'https://dialogflow.googleapis.com/v2/projects/chatbot-d5783/agent/sessions/' + sessionid + ':detectIntent';
    print(session);
    // Build the request
    final inputText = new GoogleCloudDialogflowV2beta1TextInput()
      ..text = 'Hi'
      ..languageCode = 'en';
    final queryInput = new GoogleCloudDialogflowV2beta1QueryInput()
      ..text = inputText;
    final request = new GoogleCloudDialogflowV2beta1DetectIntentRequest()
      ..queryInput = queryInput;
    // Perform the RPC to dialogflow.
    final response = await df.projects.agent.sessions.detectIntent(request, session);
    // Use the response.
    print(response.queryResult.fulfillmentText);
    await authenticatedHttpClient.close();

BR//
Mukut

**Comment by gazialankus** [comment]
For anyone coming across here, I have it working fine on my end. One problem I see in the above code is that session should not have the whole url. This session variable works for me: 
```
final session = "projects/$projectId/agent/sessions/$session"
```

So, I bet if you replace the line above: 
```
final session ='https://dialogflow.googleapis.com/v2/projects/chatbot-d5783/agent';
```
with this, it may work:
```
final session ='projects/chatbot-d5783/agent/sessions/mysession';
```

**Comment by AlexHartford** [comment]
@gazialankus Thanks a lot for your comment! I read [elsewhere](https://stackoverflow.com/questions/51868606/dialogflow-how-to-get-session-id) that the session ID didn't matter. True! But, your session string must match the format you provided: 
> projects/$projectId/agent/sessions/$session

I know I'm not OP, but your answer provides the solution to his problem. This issue should be closed. Thanks again!
