### ISSUE TITLE
Needed Support for implementing Google Picker API In Flutter 

### ISSUE THREAD

**Issue by Dhinesh-J** [google/googleapis.dart#450]
I have Found official support for Google Drive and not for Google Picker. (Link Provided below)
 https://pub.dev/packages/googleapis

Currently able to upload and see files in my drive on authentication with drive scope using the google sign-in package.

From official google docs for google picker API, support provided for JS 
https://developers.google.com/drive/picker/guides/overview#gdata

Is there any way to implement google picker API in flutter?

**Comment by kevmoo** [comment]
I think you'll have to implement it yourself – or see if anyone has built something on pub.dev

**Comment by Dhinesh-J** [comment]
Hi Kevmoo, 

I'm in need of  some support for own implementation . 

From official google docs for google picker API, support provided for JS
https://developers.google.com/drive/picker/guides/overview#gdata
Note that JS were only supported by Flutter Web and not on Flutter Mobile.  Can you please assist ?

Currently there are no package available to pick on pub.dev for google picker API .
