### ISSUE TITLE
Access blocked: [APP_NAME] ’s request is invalid | Loopback IP issue

### ISSUE THREAD

**Issue by nitinf22labs** [google/googleapis.dart#452]
```
Flutter Version 2.8.1
googleapis_auth: ^1.1.0
```

You can’t sign in because Mentor Connect by Compatibility sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Mentor Connect by Compatibility , see [error details](https://accounts.google.com/).
Error 400: invalid_request

**Comment by kevmoo** [comment]
Do NOT use googleapis_auth w/ Flutter. Use [package:extension_google_sign_in_as_googleapis_auth](https://pub.dev/packages/extension_google_sign_in_as_googleapis_auth) instead
