### ISSUE TITLE
Possible misleading documentation for `datasetId` parameter of `fitness.v1.UsersDataSourcesDatasetResource.patch()`

### ISSUE THREAD

**Issue by Frozen-Burrito** [google/googleapis.dart#453]
I am using the `fitness.v1` library in my Flutter app to add hydration data to Google Fit, and I have followed [this guide](https://developers.google.com/fit/scenarios/add-hydration-data).  Both the [Google Fit REST API reference for the Dataset patch request](https://developers.google.com/fit/rest/v1/reference/users/dataSources/datasets/patch?hl=en) and the [fitness.v1 library documentation](https://pub.dev/documentation/googleapis/latest/fitness.v1/UsersDataSourcesDatasetsResource/patch.html) mention that the `datasetId` parameter of the `patch()` request/method "is not used, and can be safely omitted."

While testing my app, invoking the following piece of code kept resulting in an `HTTP - 404` `ApiRequestError`:

```dart
final newDataset = await _fitnessApi?.users.dataSources.datasets.patch(
  newHydrationDataSet,
  _userId, // <- "me"
  _hydrationDataSourceId!,
  "",
);
```
Since I was listing the available `DataSources` previous to this, I am almost certain that `_hydrationDataSourceId` referenced an available Google Fit `DataSource` previously created by my app. Given that the `userId` is always "me", I tried providing a real `datasetId` by using the startTimeNs-endTimeNs format, instead of providing an arbitrary `String` value for `datasetId`. After doing this, the following requests were successful and the DataSet was beig added correctly to Google Fit.

I am not sure whether this is how it is intended to work and I am misinterpreting the API and its documentation, or if this is an actual issue and either the API Reference is slightly misleading or the implementation of the `datasetId` parameter of the `patch()` method in Dart does not make complete sense (it is implemented as a required positional argument, which does not convey that it can just be omitted).

Thanks in advance for any insight into this.

**Environment**
- Dart SDK: 2.17.3
- Flutter version: Channel stable, 3.0.2
- googleapis package version: 9.2.0
- Mobile device: Samsung A30s, Android 11

**Comment by kevmoo** [comment]
Sadly, we're stuck w/ what we're given in the source json. These APIs are auto-generated with very little review. 

You may want to use the `send feedback` button on https://developers.google.com/fit/rest/v1/reference/users/dataSources/datasets/patch?hl=en
