### ISSUE TITLE
Platform.environment is empty in clientViaApplicationDefaultCredentials method

### ISSUE THREAD

**Issue by Tatsiana-Karatysh** [google/googleapis.dart#458]
Trying to get events from google calendar using clientViaApplicationDefaultCredentials

final AutoRefreshingAuthClient httpClient = await clientViaApplicationDefaultCredentials(
      scopes: [CalendarApi.calendarEventsScope],
);

but get error "Null check operator used on a null value" on string:
Uri.directory(Platform.environment['HOME']!)

how can i fix it?

flutter: Null check operator used on a null value
flutter: 
#0      clientViaApplicationDefaultCredentials (package:googleapis_auth/auth_io.dart:77:49)
#1      GoogleCalendarProviderImpl.getEvents (package:data/src/providers_impl/google_calendar_provider_impl.dart:17:15)
#2      GoogleCalendarRepositoryImpl.getEvents (package:data/src/repository/google_calendar_repository_impl.dart:14:42)
#3      GetGoogleCalendarEventsUseCase.execute (package:domain/src/usecase/calendar/get_calendar_events_use_case.dart:12:31)
#4      CalendarBloc._handleInitEvent (package:profile/src/calendar/bloc/calendar_bloc.dart:52:33)
<asynchronous suspension>
flutter: ----------------------------------------------------

**Comment by kevmoo** [comment]
We're assuming you have a `HOME` environment van is set.

Are you running on Windows?

**Comment by kevmoo** [comment]
...actually, it seems like not.

**Comment by Tatsiana-Karatysh** [comment]
no, i work on mac

**Comment by JaysonBH** [comment]
@Tatsiana-Karatysh clientViaApplicationDefaultCredentials is Not for use with Flutter. clientViaApplicationDefaultCredentials is for server applications, ideally running within Google Cloud or with a GCP Service Account.

You may want to look into ussing a user authenticated flow using the `google_sign_in` package or Firebase Auth
