### ISSUE TITLE
[storage.v1] Generated API uses core.Object instead of storage.v1.Object

### ISSUE THREAD

**Issue by slightfoot** [google/googleapis.dart#461]
The generated code for the storage.v1 API and possibly others has defaulted to 

As seen here in the return type of (storage.v1.ObjectsResource.get)[https://pub.dev/documentation/googleapis/latest/storage.v1/ObjectsResource/get.html] where it should be using (storage.v1.Object)[https://pub.dev/documentation/googleapis/latest/storage.v1/Object-class.html].

Currently to make the Google Storage API work you need to cast the result. To be clear it is not just this API but all Storage APIs that refer to the `Object` type.

**Comment by kevmoo** [comment]
Ping me on twitter. Let's figure this out...

**Comment by kevmoo** [comment]
NOT A BUG! By design!

This is a WEIRD function. It support two flavors "normal" and "with medatada" so the returned type can be different.

It's weird.

One could argue – for Dart – that we should just generate two flavors of functions here so we could have better types.

**Comment by slightfoot** [comment]
ah, I see. Sorry for the "wild goose chase". It doesn't help the return type is the same name as the generic. Perhaps it should have `get` and `download` methods.

**Comment by kevmoo** [comment]
Something like that!
