### ISSUE TITLE
Partial Download does not include range header (null value)

### ISSUE THREAD

**Issue by JeanNicolasdeLamballerie** [google/googleapis.dart#462]
Hello guys ! Before anything, I'd like to preface this by saying it might be an error in implementation from my part; if this is the case I have misunderstood how the flow of the drive API works. I have tried getting help on Stackoverflow, but no one ever answered my post.

Here's my issue :

I am creating a small application based on audio files stored on Google Drive, in Flutter.

I am using the [drive api][1] to make my requests, with these scopes in my google sign in :

    GoogleSignIn _googleSignIn = GoogleSignIn(
      scopes: [
        'email',
        'https://www.googleapis.com/auth/userinfo.profile',
        'https://www.googleapis.com/auth/contacts.readonly',
        'https://www.googleapis.com/auth/drive',
        'https://www.googleapis.com/auth/docs',
        'https://www.googleapis.com/auth/drive.appdata',
      ],
    );
I have an auth element and handle signing in and out. Until then, no issues.

I can also request my files with an implementation looking like this, where I implemented a passed down API instance : 

      var api = widget.api.getAPI();
      var files = await api.files.list($fields: '*');

This works perfectly, and so does :

      var api = widget.api.getAPI();
      var files = await api.files.get("myFileId"); (//does get a file instance)

But since I'd like to retrieve some of the Metadata included in my audio files, and since the drive API doesn't natively support extracting audio metadata and sending it as a google metadata, I thought I'd extract it with a partial download on the file itself.

Here's the catch : I can't seem to get the partial download to work.
[Based on the doc][2], I thought the implementation would look something like this : 

    import 'package:googleapis/drive/v3.dart' as ga;    
    (...)
    try {
                var partiallyDownloadedFile = await api.files.get(
                    "myFileIdHere",
                    downloadOptions: ga.PartialDownloadOptions(ga.ByteRange(0, 10))); //should get a ga.Media instance
                print("partial download succeeded");
                print(partiallyDownloadedFile);
                //(...do stuff...)
                return;
              } catch (err) {
                print('Error occured : ');
                print(err);
                return;
              }

But this always throws this error : 

> ApiRequestError(message: Attempting partial download but got invalid
> 'Content-Range' header (was: null, expected: bytes 0-10/).)

I tried using it on Wav files, but also MP4 files. The error is always the same, which leads me to believe it's my implementation that's somehow wrong, but I'm not sure what I'm supposed to do to fix it. Is it my request missing the header ? The response not including it ? 
While very clear, that error doesn't help me troubleshoot my issue at all. I can't seem to find any documentation on how to conduct a partial media request. I haven't found any example projects to compare it with.

[PartialDownloadOptions][3] does not have much documentation.

I could make a partial request through the download links with a homemade http request (which is how I can read the music to begin with) but the drive API supposedly allows this. Could anyone help me correct my implementation, or confirm this is a bug ?

  [1]: https://pub.dev/documentation/googleapis/latest/drive.v3/drive.v3-library.html
  [2]: https://pub.dev/documentation/googleapis/latest/drive.v3/FilesResource/get.html
  [3]: https://pub.dev/documentation/_discoveryapis_commons/latest/_discoveryapis_commons/PartialDownloadOptions-class.html

**Comment by kevmoo** [comment]
I tried this out – and it worked fine - https://github.com/google/googleapis.dart/pull/467

```
* Credentials expire in 0:59:38.996594 *
{
 "id": "14M5lqQutVBqb_PPYH6GT51_mX2WkbXbL",
 "kind": "drive#file",
 "mimeType": "application/octet-stream",
 "name": "Google APIs test file on 2022-11-02 15:36:25.486859"
}
properties: null
      size: 1024
11
all deleted
```

**Comment by kevmoo** [comment]
would you include the full stack trace? That might help...

**Comment by JeanNicolasdeLamballerie** [comment]
`Error: ApiRequestError(message: Attempting partial download but got invalid 'Content-Range' header (was: null, expected: bytes 0-10/).)
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/_discoveryapis_commons/src/api_requester.dart 114:9                                                               request
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                          runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 639:7                                     callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
`

This is the stacktrace I get. 
My dart is 2.18.2, flutter 3.3.6.
I'll try to simplify where I get the http client into the code to see if it's not me messing something up. Thanks for the help !

**Comment by kevmoo** [comment]
Ah! Look at chrome console. Do you see errors/warnings about not being allowed to set certain headers? the browser controls the headers that client code can send

**Comment by JeanNicolasdeLamballerie** [comment]
I am currently using Edge and Chrome for debugging, and it turns out to be weirder than I thought ;
Actually, the request itself completes, with the proper params :
![image](https://user-images.githubusercontent.com/55099344/199797839-c5361653-85db-4d0b-b33c-e9a591306932.png)
![image](https://user-images.githubusercontent.com/55099344/199797950-6f08f4c1-6f66-4b96-8c37-71a0d9eed231.png)
I do even get the response :
![image](https://user-images.githubusercontent.com/55099344/199798092-0888020b-e3c9-4422-9927-0add9e72f537.png)
I have no specific error related to headers, only a dart error popping up : 
![image](https://user-images.githubusercontent.com/55099344/199798399-1f3e032e-05ee-4774-988f-5bd923c4d455.png)
I haven't tested on android for now, as I upgraded this project and need to also make sure to use JDK11 first.

**Comment by kevmoo** [comment]
Ha! "Content-Range" vs 'content-range' !!!

That's annoying. I can try a fix quick...

**Comment by kevmoo** [comment]
@JeanNicolasdeLamballerie – could you patch in https://github.com/google/googleapis.dart/pull/468 and try it out?

**Comment by kevmoo** [comment]
```yaml
dependency_overrides:
  _discoveryapis_commons:
    git:
      url: https://github.com/google/googleapis.dart
      ref: i462_fix_header_casing
      path: discoveryapis_commons
```

**Comment by JeanNicolasdeLamballerie** [comment]
Sorry @kevmoo , I was indeed struggling with my pubspec.yaml.
I've been trying to move it around, but I keep getting that same error. 
![image](https://user-images.githubusercontent.com/55099344/199813518-1beb05a0-3de3-4c4e-8069-e7c4bbc4af01.png)
I ran `flutter clean` & `flutter pub get`.

**Comment by kevmoo** [comment]
Check your pubspec.lock file – is it pointing at the github link?

Is the error exactly the same? Can you include it? I'd love to have line numbers with the new code...

**Comment by JeanNicolasdeLamballerie** [comment]
Pubspec looks fine, and importing
`import 'package:_discoveryapis_commons/_discoveryapis_commons.dart' as commons;`
shows me the code including your fix.
![image](https://user-images.githubusercontent.com/55099344/199842655-c1e2eec2-ad40-4d7f-81ab-a0ebc5b01f1d.png)
I went and added a print of the headers themselves, and this was the result :
![image](https://user-images.githubusercontent.com/55099344/199844411-39a560a3-b86f-4a67-8a2f-9341b806125c.png)

But I think I have an idea, because this timestamp doesn't fit the (correct) request; it fits the preflight request :
![image](https://user-images.githubusercontent.com/55099344/199844767-7eeb78d7-fd01-4adc-9725-e5a98c03f098.png)

Could it be that preflight messing with the `request()` function?

**Comment by JeanNicolasdeLamballerie** [comment]
Disregard this, it doesn't, I just messed up the two requests because the preflight completed after the request.
Actually, the headers in the dart code simply do not include the "content-range" at all, but are still fired with it. I have no idea where they are added.

**Comment by kevmoo** [comment]
See here: https://stackoverflow.com/questions/53259737/content-range-working-in-safari-but-not-in-chrome

I'll dig some more!

**Comment by JeanNicolasdeLamballerie** [comment]
It might be related to the access-control-expose-header from the response not including Content-Range. I commented the error and the request does return the proper stream in that case. I manage to get the first few bytes.

**Comment by kevmoo** [comment]
Now it's fixed! I also checked it

**Comment by kevmoo** [comment]
> It might be related to the access-control-expose-header from the response not including Content-Range. I commented the error directly in the library and the request does return the proper stream in that case. I manage to get the first few bytes. Maybe the lib should use the Content-Length instead to check if the range value is correct ?

`access-control-expose-header` – YUP!
