### ISSUE TITLE
How can I use it for macos desktop application?

### ISSUE THREAD

**Issue by normidar** [google/googleapis.dart#463]
I am trying to create an application for macOS, what should I do?

**Comment by kevmoo** [comment]
I'd use `obtainAccessCredentialsViaUserConsent` – you'll need to prompt the user to navigate to a URI and it should "just work"

**Comment by normidar** [comment]
@kevmoo 
is it useful for desktop ?

**Comment by kevmoo** [comment]
You mean all of these APIs? Perhaps. You can connect to gmail, sheets, docs, calendar, youtube, etc etc – fun things to play with!
