### ISSUE TITLE
Error: "insufficient_scope" when accessing androidpublisher despite scopes & IAM permissions

### ISSUE THREAD

**Issue by jimmyff** [google/googleapis.dart#466]
Hi, I've run in to an issue attempting to verify Google Play payments in a Cloud Run instance. I already successfully use this `googleapis` package in numerous CloudRun instances and utilise many of the GCP services with it ,however when I try and use the `androidpublisher` API I get the following error:

<details>
<summary>Access was denied (www-authenticate header was: Bearer realm="https://accounts.google.com/", error="insufficient_scope", scope="https://www.googleapis.com/auth/androidpublisher").</summary>

```

Access was denied (www-authenticate header was: Bearer realm="https://accounts.google.com/", error="insufficient_scope", scope="https://www.googleapis.com/auth/androidpublisher").
package:googleapis_auth/src/auth_http_utils.dart 40                      AuthenticatedClient.send
===== asynchronous gap ===========================
package:_discoveryapis_commons/src/api_requester.dart 69                 ApiRequester.request
===== asynchronous gap ===========================
package:googleapis/androidpublisher/v3.dart 4191                         PurchasesProductsResource.get
===== asynchronous gap ===========================
package:cloud_functions_core/src/payments/providers/google_play.dart 33  GooglePlayPaymentProvider._updateConsumablePurchase
===== asynchronous gap ===========================
package:cloud_functions_core/src/payments/providers/google_play.dart 22  GooglePlayPaymentProvider.updateReceipt
===== asynchronous gap ===========================
package:cloud_functions_core/src/payments/payment_processor.dart 92      PaymentProcessor.processPurchaseReceipt
===== asynchronous gap ===========================
package:payment_queue/functions.dart 40                                  function

```
</details>

I'm creating the authenticated client with the necessary scopes:

<details>
<summary>Dart code to generate authenticated client</summary>

```dart

class GapiLiveService implements GapiService {
  final List<GapiServices> scopes;
  final String? credentials;

  GapiLiveService(this.scopes, {this.credentials});

  @override
  Future<AutoRefreshingAuthClient> get client async {
    List<String> _scopes = <String>[];

    for (final s in this.scopes) {
      _scopes.addAll(GapiService.serviceScopes[s]!);
    }

    print(
        'Created GAPI client (${credentials != null ? 'Creds provided' : 'viaAppDefault'}) with scopes: ($_scopes)');

    return (credentials != null)
        ? await _fromCredentials(_scopes)
        : await clientViaApplicationDefaultCredentials(
            scopes: _scopes, baseClient: http.IOClient());
  }
```
</details>

This code prints out the following log entry: 

```
Created GAPI client (viaAppDefault) with scopes: (
  [
    https://www.googleapis.com/auth/datastore, 
    https://www.googleapis.com/auth/cloud-platform, 
    https://www.googleapis.com/auth/androidpublisher
  ]
)
```

I have a IAM profile specifically for this Cloud Run instance with the necessary permissions:

 * Android Management User
 * Cloud Filestore Editor
 * Firebase Admin
 * Pub/Sub Publisher
 * Secret Manager Secret Accessor

(However I don't think these are part of the issue as this is a scope error rather than permission error)

Before the instance hits the scope error, it successfully makes a couple of Firestore requests so I know the permissions and scopes are working as expected for that service.

I've been looking at this bug all afternoon and I've checked everything numerous times. I hoped maybe someone might spot something I'm doing wrong or perhaps I've stumbled upon a bug with this API?

Thanks

**Comment by kevmoo** [comment]
I don't *think* this has anything to do with this package, in general. If there's a bug, let us know.

Otherwise, I'd start at https://developers.google.com/android-publisher – dig into support options, etc!

**Comment by jimmyff** [comment]
Hallelujah!! _Phew_ I finally got to the bottom of it and got this working. 

I think it could be described as a bug @kevmoo -or at least a misleading error message. The error I get through the GCP ['test this method' tool](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products/get) was this:

```json
{
  "error": {
    "code": 403,
    "message": "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.",
    "errors": [
      {
        "message": "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.",
        "domain": "androidpublisher",
        "reason": "projectNotLinked"
      }
    ]
  }
}
```

-which was much more useful than the `insufficient_scope` error I was getting from googleapis package. Ideally the `googleapis` package could provide this specific error? If not then it would be useful to add a notice to the documentation explaining this API has specific credentials requirements? Unlike all the others APIs in the googleapis package, this API can only be queried by using credentials that are linked to your google play developer account and setting that all up is non-trivial.

### In case anyone else ends up here with the same issue, this was my solution:
It turns out can only have a single project linked to your Google Play developer account.  Here was my solution: 

 * Go to Google Play Developer Console -> Settings -> API Access and link or create a cloud project (NB: Not the same one your app uses, this should be a generic project)
 * Create a service worker using this new google cloud project
 * Go back to Play Console API Access and grant this service worker access to view financial information and manage orders.
 * Also on the API access screen add permission to your individual apps that this service worker will be querying
 * Downloaded the JSON key file for this service worker &  add this to the Google secrets manager & expose the secret to my cloud run instance
 * Retrieve the service worker key in code and then provide it when creating the GAPI client (including the necessary androidpublisher scope).
 * If you get permission denied error at first, it could be [this bug](https://stackoverflow.com/questions/43536904/google-play-developer-api-the-current-user-has-insufficient-permissions-to-pe) or could be that you need to wait up to 48 hours for the google play permissions to activate (this is so ridiculous!).
