### ISSUE TITLE
Deprecated on web

### ISSUE THREAD

**Issue by Cagatay342** [google/googleapis.dart#470]
Hi i made an simply example it works but i get this warning

Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.

i had an email from google about this i guess this package needs update at web part

**Comment by kevmoo** [comment]
Yup. I have the code for this landed: https://github.com/google/googleapis.dart/pull/447

Just need to publish a version!
