### ISSUE TITLE
Getting error while debugging for any device other than web

### ISSUE THREAD

**Issue by xenSlayer** [google/googleapis.dart#471]
![image](https://user-images.githubusercontent.com/39700587/202716002-589bfe97-487d-4fba-861d-845130e0f43b.png)

I am getting this error while running in windows or android. I tried `flutter clean` but its showing the same error. Got no issue in web though. 

used version: 
googleapis_auth: ^1.3.1

edit: does this package work for windows or its it just for web?

**Comment by xenSlayer** [comment]
does this package works for windows or its it just for web?

**Comment by kevmoo** [comment]
It should work everywhere!

**Comment by xenSlayer** [comment]
seems like the `import 'package:googleapis_auth/auth_browser.dart';` import is for the web only with web based libraries that might be resulting in the build fails for other device. I'll check on it and post an update the issue status. Thank you.

**Comment by xenSlayer** [comment]
The problem is I am building flutter app for both web and other console based device. Now as the googlapis_auth docs says there are two ways for authenticating a client based on the device. i.e for web: 
```
import 'package:googleapis_auth/auth_browser.dart';

// Initialize the browser oauth2 flow functionality then use it to obtain credentials.
Future<AccessCredentials> obtainCredentials() async {
  final flow = await createImplicitBrowserFlow(
    ClientId('....apps.googleusercontent.com'),
    ['scope1', 'scope2'],
  );

  try {
    return await flow.obtainAccessCredentialsViaUserConsent();
  } finally {
    flow.close();
  }
}
```

and for console based device :
```
import 'package:googleapis_auth/auth_io.dart';
import 'package:http/http.dart' as http;

// Use the oauth2 authentication code flow functionality to obtain
// credentials. [prompt] is used for directing the user to a URI.
Future<AccessCredentials> obtainCredentials() async {
  final client = http.Client();

  try {
    return await obtainAccessCredentialsViaUserConsent(
      ClientId('....apps.googleusercontent.com', '...'),
      ['scope1', 'scope2'],
      client,
      _prompt,
    );
  } finally {
    client.close();
  }
}
```

The problem now is the `import 'package:googleapis_auth/auth_browser.dart';` consists web based api which cannot be compiled when running flutter windows build or android build. 

I tried this fix: 
```
// for console based login
import 'package:googleapis_auth/auth_io.dart'
// for browser based login
    if (dart.library.html) 'package:googleapis_auth/auth_browser.dart';
```
But this so far is not helping. Is there any way to fix this issue.

**Comment by xenSlayer** [comment]
https://itecnote.com/tecnote/flutter-how-to-import-platform-specific-dependency-in-flutter-dart-combine-web-with-android-ios/ this solved my problem. I wish the package had better implementation to handle platform based sign in out of the box. Thank you.

**Comment by kevmoo** [comment]
See the Read me for this package on GitHub. You should not use the auth
code here. You should use the flutter Google sign in package.!!
