### ISSUE TITLE
No way to upload photos to photoslibrary

### ISSUE THREAD

**Issue by derrickgw** [google/googleapis.dart#476]
The photos library has a glaring omission.  There is no way to upload photos.  This is easy to verify by searching the file for the `v1/uploads` endpoint url. I suspect that this is because [the api discovery document](https://photoslibrary.googleapis.com/$discovery/rest?version=v1) does not mention that endpoint.

Can we manually add that endpoint?  Or at the very least make the `_requester` object available so that users have the option of adding this and possibly other missing endpoints? Not only is the current object private, it is defined in a private package.

**Comment by kevmoo** [comment]
@derrickgw – I'm not comfortable adding one-off APIs that aren't in the document. Sorry.

**Comment by derrickgw** [comment]
Unfortunately that make this library kind of useless.  If I have to go through the hassle of getting the authentication headers and instantiating my own http client, then I just ended up doing all the of the hard work that the library was theoretically supposed to do for me.  I can implement the other 1-2 endpoints I need and reduce my dependency list by one. ☹️

**Comment by kevmoo** [comment]
@derrickgw – you're welcome to fork the code, of course!
