### ISSUE TITLE
[cloud vision api] A runnable Example using Cloud vision API for beginner

### ISSUE THREAD

**Issue by KennyTC** [google/googleapis.dart#485]
I want to make a Flutter app where I detect text and number from an image using Google Cloud vision API.

I see the documents  of Google Cloud Vision is here https://cloud.google.com/vision/docs/ocr#vision_text_detection-drest
and the  API for dart  is here https://pub.dev/documentation/googleapis/latest/vision.v1/vision.v1-library.html

I also see one  example  here.
https://github.com/google/googleapis.dart/issues/67

However, for a Flutter  beginner, there  are  many places which  are  hard  to understand.
Can anyone provide a runnable example code  (which authenticate google account,  and  then uses Cloud  vision API)?

**Comment by kevmoo** [comment]
Hey @KennyTC – sadly, we just offer simple wrappers that are auto-generated. If you are using Flutter, I'd look at https://docs.flutter.dev/development/data-and-backend/google-apis to start!
