### ISSUE TITLE
[Bug] `FirebaseRemoteConfigApi.projects.remoteConfig.downloadDefaults` incorrectly handles JSON responses

### ISSUE THREAD

**Issue by Pante** [google/googleapis.dart#488]
In the code snippet below, `response` will always be empty. Further investigation reveals that it's because of https://github.com/google/googleapis.dart/blob/master/generated/googleapis/lib/shared.dart#L9636 expecting data to be mapped to a `data` key.

```dart
final client = FirebaseRemoteConfigApi(<my client>);
final response = await client.projects.remoteConfig.downloadDefaults(_project, format: 'json'); // response will always be empty
```

Edit: internal tracking bug - http://b/267378194

**Comment by kevmoo** [comment]
I've had to create overrides for APIs that are broken like this - see https://github.com/google/googleapis.dart/tree/master/overrides

I need to understand what the data coming over the wire looks like so I can make a patch here.

**Comment by Pante** [comment]
It's just a simple JSON object with no nesting. Something like
```json
{
  "a": "limited_time_offering",
  "b": "default_offering",
  "c": "true",
  "d": "1"
}
```

**Comment by kevmoo** [comment]
@Pante – would you send a permalink to the line? I think the source changed!

**Comment by Pante** [comment]
No problem! The affected method is [`downloadDefaults(...)`](https://github.com/google/googleapis.dart/blob/ea867513272a5075bc2b2229dddc9b53780312d7/generated/googleapis/lib/firebaseremoteconfig/v1.dart#L279) which is caused by [`HttpBody.fromJson(...)`](https://github.com/google/googleapis.dart/blob/ea867513272a5075bc2b2229dddc9b53780312d7/generated/googleapis/lib/shared.dart#L9727).

**Comment by kevmoo** [comment]
A version w/ this fix has been published: https://pub.dev/packages/googleapis/versions/10.1.0
