### ISSUE TITLE
DriveApi requests can be invoked without any oauth scopes

### ISSUE THREAD

**Issue by rasitayaz** [google/googleapis.dart#489]
I was trying to use `DriveApi.driveFileScope` (https://www.googleapis.com/auth/drive.file). The scope description says, _"See, edit, create, and delete only the specific Google Drive files you use with this app"_. However, when I call [list method](https://pub.dev/documentation/googleapis/latest/drive.v3/FilesResource/list.html), I was able to access every single file in my Drive.

I am using [google_sign_in](https://pub.dev/packages/google_sign_in) to determine scopes. I have also tried signing in without including any scopes and I was still able to access and create files with `DriveApi`.

```dart
import 'package:google_sign_in/google_sign_in.dart';
import 'package:googleapis/drive/v3.dart';

void listFiles() async {
  final auth = GoogleSignIn(scopes: [DriveApi.driveFileScope]);
  // You can also try without passing a scope: GoogleSignIn();
  final account = await auth.signIn();
  if (account != null) {
    final client = GoogleClient(await account.authHeaders);
    final drive = DriveApi(client);
    final result = await drive.files.list();
    for (final file in result.files ?? <File>[]) {
      print(file.name);
    }
  }
}

class GoogleClient extends IOClient {
  GoogleClient(this.authHeaders);

  final Map<String, String> authHeaders;

  @override
  Future<IOStreamedResponse> send(BaseRequest request) {
    return super.send(request..headers.addAll(authHeaders));
  }

  @override
  Future<Response> head(Uri url, {Map<String, String>? headers}) {
    return super.head(url, headers: headers?..addAll(authHeaders));
  }
}
```

**Comment by kevmoo** [comment]
As with all of these APIs, we just provide helpers for calling JSON.

I'd dig into https://developers.google.com/drive/ and see if there ways to ask questions – maybe stackoverflow?
