### ISSUE TITLE
Issue uploading files (resumable) through drive API

### ISSUE THREAD

**Issue by GSirma** [google/googleapis.dart#516]
I'm experience issue uploading files through drive API (resumable mode). Everything was working till the last Wednesday.

googleapis: ^1.0.0

![Annotation 2023-03-02 165705](https://user-images.githubusercontent.com/95858788/223058029-7737bf79-6e19-4caa-9818-c47e9a84d7a6.jpg)
![Annotation 2023-03-02 165743](https://user-images.githubusercontent.com/95858788/223058697-52a9aa3b-c111-41a1-a9cf-5a366ace3590.jpg)
![Annotation 2023-03-02 165917](https://user-images.githubusercontent.com/95858788/223058704-ff5e8536-bc49-4545-8b5a-cd31f921dbd1.jpg)

**Comment by kevmoo** [comment]
First, bump that dependency to `^10.0.0`

**Comment by GSirma** [comment]
> 

I can't update to latest version. I tried with `^8.1.0` version but issue was the same.

Frankly I don't think that will help me because both `^1.0.0` and `^10.0.0` will make same API call for resumable upload.

![image](https://user-images.githubusercontent.com/95858788/223376419-ef448e7b-1679-465b-9a03-3046db121b1d.png)

Is that URL deprecated and if it is will somebody make a patch?

**Comment by kevmoo** [comment]
Check out the example here to see if it helps: https://github.com/google/googleapis.dart/blob/master/test_integration/test/storage_test.dart

it's for storage, but the resumable bits should be similar.

**Comment by GSirma** [comment]
It was issue with Drive API which Google back end developer resolved over the weekend.
