### ISSUE TITLE
[firestore] type coercion failure in RunAggregationQueryResponse

### ISSUE THREAD

**Issue by mockturtl** [google/googleapis.dart#517]
When I run a Firestore `count` ("aggregation query")...

```dart
var req = RunAggregationQueryRequest(
     structuredAggregationQuery: StructuredAggregationQuery(
         aggregations: [Aggregation(alias: 'count', count: Count())],
         structuredQuery: StructuredQuery(
             from: [CollectionSelector(collectionId: 'foo')],
             where: ...)));

var res = await _firestoreApi.projects.databases.documents.runAggregationQuery(req, _parent);
```

...I get an error:

```
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast
#0      ProjectsDatabasesDocumentsResource.runAggregationQuery (package:googleapis/firestore/v1.dart:1575:19)
<asynchronous suspension>
```

Printing `response_` ([source](https://github.com/google/googleapis.dart/blame/googleapis-v10.1.0/generated/googleapis/lib/firestore/v1.dart#L1580)), I confirm it was decoded as a single-element `List`, instead of `Map`:

```dart
core.print(response_);
// [{result: {aggregateFields: {count: {integerValue: 5}}}, readTime: 2023-03-07T01:38:31.046168Z}]
```

### possible fix

I suspect it's because the [rpc](https://github.com/googleapis/googleapis/blob/master/google/firestore/v1/firestore.proto#L154) is `stream`-valued.

I don't entirely follow the codegen yet (it changes more than I expect), but I have a patch that makes the Dart side compatible with the actual bytes.

PR incoming.

### environment

Occurs with Firestore emulator and real instances.  Dart versions 2.19.2 / 2.19.3 / 3.0.0-277.0.dev-1.

**Comment by kevmoo** [comment]
@mockturtl – would you check https://github.com/google/googleapis.dart/pull/519 to see if it does what you need it to?
