### ISSUE TITLE
Odd generated result for Firestore Value class - integerValue property

### ISSUE THREAD

**Issue by walsha2** [google/googleapis.dart#520]
https://github.com/google/googleapis.dart/blob/7b506367ccf8aa0bdb6a4ad867e8e34933c2d884/generated/googleapis/lib/firestore/v1.dart#L4745-L4746

The result above does not make sense. An expected integer value in Firestore is being mapped to a `String` in Dart. I know this code is generated, but when looking at the [source interface definitions](https://github.com/googleapis/googleapis) it is indeed an integer value:

```rpc
// An integer value.
int64 integer_value = 2;
```

https://github.com/googleapis/googleapis/blob/a1df408f367ac5eb07ae93084a1678b87adbfcc3/google/firestore/v1/document.proto#L91-L92

----------

Is this a bug or some sort of code generation artifact that prohibits `int64` gRPC proto definition from mapping to Dart's native `int`?

**Comment by kevmoo** [comment]
Weird, I know. Since these libraries are designed to work everywhere Dart works, even 64-bit ints are stored as `String` so they do not lose accuracy when compiled to JS.
