### ISSUE TITLE
Getting deprecation warning on clientViaUserConsent()

### ISSUE THREAD

**Issue by arualana** [google/googleapis.dart#521]
I am getting this warning in the console (Flutter web)
```
import 'package:googleapis_auth/auth_browser.dart';

// Initialize the browser oauth2 flow functionality then use it to
// get an authenticated and auto refreshing client.
Future<AuthClient> obtainAuthenticatedClient() async {
  final flow = await createImplicitBrowserFlow(
    ClientId('....apps.googleusercontent.com'),
    ['scope1', 'scope2'],
  );

  try {
    return await flow.clientViaUserConsent();
  } finally {
    flow.close();
  }
}
```

`
You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.`

**Comment by kevmoo** [comment]
I just published v1.4 of googleapis_auth which has new APIs for this case: https://pub.dev/packages/googleapis_auth/versions/1.4.0
