### ISSUE TITLE
[googleapis_auth] cannot decode AccessCredentials from yaml

### ISSUE THREAD

**Issue by alextekartik** [google/googleapis.dart#526]
The title might not be clear but after trying `AccessCredentials.fromJson` from a map decoded by yaml I get the following exception:

This can be seeing in the following test:
```dart
import 'dart:convert';

import 'package:googleapis_auth/googleapis_auth.dart';
import 'package:test/test.dart';
import 'package:yaml/yaml.dart';

void main() {
  test('raw', () {
    var accessCredentials = AccessCredentials(
        AccessToken('a', 'b', DateTime.now().toUtc()), 'c', ['d']);
    var map = accessCredentials.toJson();
    var yamlMap = (loadYaml(jsonEncode(map)) as Map).cast<String, Object?>();
    try {
      // This is failing with: failing: type 'YamlMap' is not a subtype of type 'Map<String, dynamic>' in type cast
      AccessCredentials.fromJson(yamlMap);
    } catch (e) {
      print('failing: $e');
    }

    // workaround by json encoding/encoding the yamlMap
    yamlMap = (jsonDecode(jsonEncode(yamlMap)) as Map).cast<String, Object?>();
    // Ok
    AccessCredentials.fromJson(yamlMap);
  });
}
```

indeed in https://github.com/google/googleapis.dart/blob/6ba2e959c7a77618650cb7bbf65386f25f355c8b/googleapis_auth/lib/src/access_credentials.dart#L30

while json['accessToken']  is a YamlMap not a Map<String, dynamic>.

The easiest solution would be to have `factory AccessCredentials.fromJson(Map<String, dynamic> json)` become `factory AccessCredentials.fromJson(Map json)` and `factory AccessToken.fromJson(Map<String, dynamic> json)` become `factory AccessToken.fromJson(Map json)` but I'm not sure what is the policy in these APIs.

Or maybe that is an issue with yaml that should implement Map<String, dynamic> instead of Map.

**Comment by kevmoo** [comment]
Yeah, `pkg:yaml` is a bit weird here, but I'm not sure why. This members accepts standard, JSON content. It's less than 100 lines to write a converter to generate the right type of `Map<String, dynamic>` here.

**Comment by alextekartik** [comment]
Thanks, it make sense as the function is explicitly named fromJson and and not fromMap. I'll ask the yaml project whether it makes sense to have YamlMap implements Map<String, dynamic>.

**Comment by kevmoo** [comment]
Warning: I think I had a conversation with the developer at the time about
this. It's likely like a five or six-year-old bug if you want to go digging.

**Comment by alextekartik** [comment]
Indeed you're right, this has been reported already: https://github.com/dart-lang/yaml/issues/90. I should have looked there first. Sorry for the trouble.
