### ISSUE TITLE
pub.dev Api reference only displaying v1,v2,v3,v4,v5 section headers.

### ISSUE THREAD

**Issue by mark-at-pieces** [google/googleapis.dart#542]
First and foremost, this package is awesome!

Went to the docs today to look at pub/sub api reference, and noticed all the section headers are missing.(I've attached a screen shot down below.)

I was still able to find pub/sub via cmd+f on macos, however I experienced a broken link and a 404 when i selected "API Details" at the route "https://pub.dev/documentation/googleapis/latest/pubsub.v1/pubsub.v1-library.html", however I noticed the route just needed a little adjusting from "." to "_" within the separating of the version number. Heres the link that worked for me "https://pub.dev/documentation/googleapis/latest/pubsub_v1/pubsub_v1-library.html".

Not 100 percent sure if this is an issue on pub.dev's side of things but wanted to put it on here just incase.

Thank you for the awesome package!!

<img width="1019" alt="Screenshot 2023-05-11 at 3 11 48 PM" src="https://github.com/google/googleapis.dart/assets/46659689/1550f5f6-82d4-44aa-9856-3d532497a3c1">

**Comment by kevmoo** [comment]
Known problem. See https://github.com/dart-lang/dartdoc/issues/1658 Thankfully you can scan the main list on the left to get to the API you want.

**Comment by jonasfj** [comment]
@kevmoo should we consider adding the `library` statements back? They are pretty harmless, but make dartdoc output prettier :D

**Comment by jonasfj** [comment]
Changing the `library` statements also broke all the links on the README page :see_no_evil:
