### ISSUE TITLE
API docs for package missing

### ISSUE THREAD

**Issue by filiph** [google/googleapis.dart#558]
Currently, when I go to https://pub.dev/packages/googleapis and click on one of the "API details" links (such as https://pub.dev/documentation/googleapis/11.3.0/docs_v1/docs_v1-library.html), I get 404 Not Found.

Clicking on "Scores" says "The analysis of the package has not been completed yet."

And it says `[[unknown platforms]]` under the package title.

<img width="385" alt="Screenshot 2023-08-03 at 22 51 34" src="https://github.com/google/googleapis.dart/assets/919717/ad30f9a8-9c27-4d2b-a226-f6823b819bdb">

I'm guessing something went wrong with the `pana` run. The last update is 22 days ago.

// cc @kevmoo

**Comment by kevmoo** [comment]
This is not me...I don't think. Something is broken w/ pub. Let me dig!

**Comment by isoos** [comment]
This is because the new sandbox-based analysis has some rough edges, we are working on fixing it.
https://github.com/dart-lang/pub-dev/pull/6877

**Comment by filiph** [comment]
Oh, thanks both for checking! You can close this if it's not useful to have this issue around.

**Comment by kevmoo** [comment]
Closing out. Follow-up on the pub side if you still see problems in the next few days

**Comment by kevmoo** [comment]
Fixed! https://pub.dev/documentation/googleapis/latest/docs_v1/docs_v1-library.html
