### ISSUE TITLE
Play Games Services v2 SDK

### ISSUE THREAD

**Issue by aeb-dev** [google/googleapis.dart#567]
I could not find anything related to games v2 API. It does not exist under beta api as well. Did I miss it somehow? If not, is it possible to add it?

**Comment by kevmoo** [comment]
Can you link to the public docs for this?

I don't see it on my discovery inputs

**Comment by aeb-dev** [comment]
I am not sure if this is what you want but here: https://developers.google.com/games/services/android/quickstart

**Comment by kevmoo** [comment]
Is this a cloud API? This package is only for cloud APIs.

**Comment by aeb-dev** [comment]
I see, I think it is not cloud API, sorry for taking your time
