### ISSUE TITLE
fullText search does not work on appDataFolder in google drive

### ISSUE THREAD

**Issue by floyd-lewis** [google/googleapis.dart#575]
It appears that the files are not getting indexed in appDataFolder. 

   final queryStr =
         "name='text.txt' and  fullText contains '$searchStr'  and  trashed = false";
      final fileList = await api.files.list(
        q: queryStr,
        $fields: 'files(id, name, parents)',
        spaces: 'appDataFolder',

If I keep the files in shared directory and use the spaces: 'drive' the search works. 
If I use a 'not fullText' instead I get back the file along with other files. 
 "name='text.txt' and not fullText contains '$searchStr'  and  trashed = false";

**Comment by kevmoo** [comment]
This API just exposes the underlying HTTP/JSON API. 

Check out the docs here: https://developers.google.com/drive/api/reference/rest/v3/files/list

Reopen if there is evidence that the Dart code is not exposing the underlying API in a way that causes problems.
