### ISSUE TITLE
Support Discovery for Media? 

### ISSUE THREAD

**Issue by loeffel-io** [google/googleapis.dart#576]
Hey, are there any plans to support discovery for media? ref: https://cloud.google.com/discovery-engine/media/docs/recommend + https://cloud.google.com/nodejs/docs/reference/discoveryengine/latest

Thanks!

**Comment by loeffel-io** [comment]
Also wondering where i can find the protos https://cloud.google.com/discovery-engine/docs/reference/rpc/google.cloud.discoveryengine.v1#google.cloud.discoveryengine.v1.CompletionService

**Comment by kevmoo** [comment]
Check out https://github.com/googleapis/googleapis ?
