### ISSUE TITLE
How to classify data on the basis of it's type

### ISSUE THREAD

**Issue by harshhrivastava** [google/googleapis.dart#581]
I am building a project which needs to read data from images and classify it in one of the category, say name, contact number, etc.

We can use Vision api in order to read the text from images, but I am not sure how can we classify it.

Can someone please help me with this?

Any documentation or article related to this would be of great help.

Thank you.

**Comment by kevmoo** [comment]
This package is 100% generated.

Look at 

https://cloud.google.com/vision/
and
https://pub.dev/documentation/googleapis/11.4.0/vision_v1/vision_v1-library.html

That's all we can offer!
