### ISSUE TITLE
[Google Play Game Services] Any tutorial available?

### ISSUE THREAD

**Issue by erperejildo** [google/googleapis.dart#583]
Apart from this link: https://pub.dev/documentation/googleapis/11.4.0/games_v1/games_v1-library.html
Do we have any other instructions on how to use this package?

**Comment by kevmoo** [comment]
Sadly, no. Everything thing here is auto-generated.

Does this help: https://developers.google.com/games/services/web/api/rest ?

**Comment by erperejildo** [comment]
There are a few different APIs:
- Google Play Game Services - games_v1
The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.
[Documentation](https://developers.google.com/games/)
[API details](https://pub.dev/documentation/googleapis/11.4.0/games_v1/games_v1-library.html)

- Google Play Game Services Publishing API - gamesconfiguration_v1configuration
The Google Play Game Services Publishing API allows developers to configure their games in Game Services.
[Documentation](https://developers.google.com/games/)
[API details](https://pub.dev/documentation/googleapis/11.4.0/gamesconfiguration_v1configuration/gamesconfiguration_v1configuration-library.html)

- Google Play Game Management - gamesmanagement_v1management
The Google Play Game Management API allows developers to manage resources from the Google Play Game service.
[Documentation](https://developers.google.com/games/)
[API details](https://pub.dev/documentation/googleapis/11.4.0/gamesmanagement_v1management/gamesmanagement_v1management-library.html)

- Game Services API - gameservices_v1
Deploy and manage infrastructure for global multiplayer gaming experiences.
[Documentation](https://cloud.google.com/solutions/gaming/)
[API details](https://pub.dev/documentation/googleapis/11.4.0/gameservices_v1/gameservices_v1-library.html)

-------

Do I need to use all of them?

My app is an online game where you can play solo and get points. These points go to a global ranking and you have some achievements to unlock. No saved games, every time you play you get these points. Just a basic game.

So the first thing is to log in the user. I checked the list but how do I do that? 

NOTE: I've got everything setup in Google Play Console and Cloud already

**Comment by erperejildo** [comment]
Also found this game made by someone working at that point in the Flutter team: https://github.com/filiph/tictactoe

This is not using this package, it uses this 3rd party package instead: https://pub.dev/packages/games_services

**Comment by kevmoo** [comment]
@erperejildo – sorry. I've only used 3-4 of these APIs directly. I have no experience with most of them. I just try to get our bindings up-to-date!

**Comment by erperejildo** [comment]
> @erperejildo – sorry. I've only used 3-4 of these APIs directly. I have no experience with most of them. I just try to get our bindings up-to-date!

could you point me to someone else maybe?
