### ISSUE TITLE
[googleapis_beta] Not published in pub.dev

### ISSUE THREAD

**Issue by davidmartos96** [google/googleapis.dart#591]
Hello!
I'm depending on `googleapis_beta` for the Error Reporting API in a `shelf` application. It looks like the published version is almost 2 years old and hasn't been published along `googleapis` when regenerating the clients. Is that expected?

Currently the published `googleapis_beta` package stills depends on `http` < 1.0.0, making it a bit troublesome to keep depending apps up to date.

**Comment by kevmoo** [comment]
I've avoiding publishing `_beta` because these APIs are not stable and I really didn't want to encourage folks to use them.

But I can see that error reporting is still around in beta...and has been for a LONG time. No idea if there are plans to make it stable, but I'm happy to do a roll here.
