### ISSUE TITLE
Allow support for non-Google auth providers

### ISSUE THREAD

**Issue by bryanoltman** [google/googleapis.dart#596]
Because the "get code, exchange code for token" flow is very standard, it would be nice if the `googleapis_auth` package could be extended to support other OAuth providers. This should just require the ability to make two URIs configurable: the auth endpoint and the token endpoint (these currently are hardcoded in the known URIs file). We've forked this package in shorebird and made this change, and would be happy to help upstream if there is interest.

Our fork: https://github.com/shorebirdtech/shorebird/tree/main/third_party/googleapis_auth

**Comment by kevmoo** [comment]
If it's a clean, non-breaking PR send away!

If it's not clean or requires breaks, let's chat.

**Comment by bryanoltman** [comment]
Aiming for clean and non breaking with https://github.com/google/googleapis.dart/pull/597 😄
