### ISSUE TITLE
Missing docs for `googleapis` v13.0.0

### ISSUE THREAD

**Issue by orenagiv** [google/googleapis.dart#599]
Hey,
It seems that since v13.0.0, something is broken on pub.dev and the links to the package docs lead to a [404 not found page](https://pub.dev/documentation/googleapis/13.0.0/abusiveexperiencereport/v1/abusiveexperiencereport/v1-library.html)

<img width="837" alt="Screenshot 2024-02-29 at 15 40 57" src="https://github.com/google/googleapis.dart/assets/2144775/d3bbd5e1-6755-4b57-8952-a793448a04a0">

<img width="446" alt="Screenshot 2024-02-29 at 15 40 04" src="https://github.com/google/googleapis.dart/assets/2144775/9b7c2443-fcba-4dfb-ac07-d707c175ded5">

**Comment by kevmoo** [comment]
Yep! Known issue. Trying to work w/ the pub team on this!

**Comment by kevmoo** [comment]
Fixed! https://pub.dev/documentation/googleapis/latest/

**Comment by orenagiv** [comment]
Thx! 🙏🙂

**Comment by orenagiv** [comment]
Hey @kevmoo 
It seems that the links to the Dart Package Details lead to a 404 🤔

Example - clicking the logger/v2 Dart Package Details:
https://pub.dev/documentation/googleapis/13.0.0/logging/v2/logging/v2-library.html

**Comment by kevmoo** [comment]
Ugh. Must be some weirdness on the server. Thanks for flagging!

**Comment by kevmoo** [comment]
This is an issue. Working on a fix
