### ISSUE TITLE
Adding Speech to Text V2 API

### ISSUE THREAD

**Issue by tamcy** [google/googleapis.dart#603]
Hello, I would like to know if there is any plan to add the Speech to Text V2 API (https://cloud.google.com/speech-to-text/v2/docs/reference/rest) to this library. Thank you!

**Comment by kevmoo** [comment]
Got you here! https://pub.dev/documentation/googleapis/latest/speech_v1/speech_v1-library.html

**Comment by tamcy** [comment]
To clarify, there are two versions of speech to text API, v1 and v2. They have different endpoints, apis, models, and pricings. I just started trying the speech to text service on gcloud, and I am aware that the v1 APIs are available in this package. I tried playing with the v1 APIs and it works. Then I wanted to try v2 to see the difference but I found there is no generated API available, hence the question. Thanks again!

**Comment by kevmoo** [comment]
This has been published in 13.1!

**Comment by tamcy** [comment]
Thanks Kevin 😊
