### ISSUE TITLE
Consider generating alpha APIs in addition to beta

### ISSUE THREAD

**Issue by mark-dropbear** [google/googleapis.dart#626]
Hey @kevmoo 

I'm in the process of building a web app with Flutter to help create and manage A/B tests and other kinds of experiences. 

Part of that work involves using the Google Analytics 4 Admin API to create and archive the concept of an `Audience` as per the official integration documentation outlined here: https://developers.google.com/analytics/devguides/collection/ga4/integration

However, it seems that this is _only_ available in the Google Analytics Admin **Alpha** API as outlined here: https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.audiences?hl=en#Audience

My ideal scenario here is to be able to just use the existing `googleapis`  package to do this and call it a day but we are currently only offering `beta` and `stable` APIs at the moment.

So I wanted to ask if you might be open to also generating the `alpha` APIs as well?

I'd also be open to your thoughts on what my options would look like here if for any reason that doesn't work for your goals with this package. The only workarounds I have identified so far are:
- Move this to the server and use gRPC as a way to autogenerated those libraries (unclear how things like oauth permission scopes work here, it seems like a lot of work unfortunately at first glance).
- Not use Flutter and instead look at JS as an option.

**Comment by kevmoo** [comment]
https://github.com/google/googleapis.dart/blob/cd1d757109c08c694afc5c28dadc2eb07470eb35/config.yaml#L341

I *could* enable this API and publish if it unblocks you in the beta API set.

I've been avoiding publishing beta unless folks ask for it.

**Comment by kevmoo** [comment]
I just landed (but did not publish)

https://github.com/google/googleapis.dart/blob/master/generated/googleapis_beta/lib/analyticsadmin/v1alpha.dart

Can you use a dependency override to confirm this gives you what you want?

https://dart.dev/tools/pub/dependencies#git-packages
https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by mark-dropbear** [comment]
Amazing, thank you, let me do some prototyping over the next few days and I will get back to you if anything is missing but based on everything I know at the moment this is exactly what I need thank you again.
