### ISSUE TITLE
All "Dart Package Details" links in googleapis.dart/generated/googleapis/README.md lead to a 404

### ISSUE THREAD

**Issue by hrushikeshrv** [google/googleapis.dart#630]
Hi, I'm not sure if this is being worked on or has already been reported, but the all of the "Dart Package Details" links in the file `googleapis.dart/generated/googleapis/README.md` are broken and lead to a 404.

Example links -  
https://pub.dev/documentation/googleapis/13.2.0/abusiveexperiencereport_v1/abusiveexperiencereport_v1-library.html  
https://pub.dev/documentation/googleapis/13.2.0/sheets_v4/sheets_v4-library.html

... and so on for all the listed libraries.

The links for the previous version (`13.1.0`) still work, and I see that the `Publish` action for the last commit [failed](https://github.com/google/googleapis.dart/actions/runs/9505108875/job/26199218116). So I'm guessing that's why the links must be broken.

Sorry if this is already being worked on 😅

**Comment by kevmoo** [comment]
I republished things, but we have a failure in doc generation:
https://pub.dev/packages/googleapis/versions/13.2.0/score/log.txt

I will bring it up w/ the team!

**Comment by kevmoo** [comment]
This appears fixed!
