### ISSUE TITLE
Please pass in a languageVersion to DartFormatter()

### ISSUE THREAD

**Issue by munificent** [google/googleapis.dart#649]
This package uses dart_style's library API in `discoveryapis_generator/lib/src/utils.dart`. In dart_style 2.7.3, we added an optional parameter to let you pass in a language version. In the upcoming 3.0.0 version of dart_style, that parameter will become mandatory.

When possible, please update this package to pass in a language version. If you always just want to format using the latest version, you can pass in `languageVersion: DartFormatter.latestLanguageVersion`.

Thanks!

**Comment by kevmoo** [comment]
Fixed (by @munificent ) in e7ae6b27ad412d9a858935a88b28297ff548cdc4
