### ISSUE TITLE
Google SignIn + Google APIs integration

### ISSUE THREAD

**Issue by IordacheClaudiu** [google/googleapis.dart#71]
How to create an HTTP Client starting from an `GoogleSignInAccount.authHeaders`?
None of the below options seems to be fit for this scenario:
1.  `clientViaApiKey(apiKey)`
2.  `clientViaMetadataServer()`
3.  `clientViaServiceAccount(clientCredentials, scopes)`
4.  `clientViaUserConsent(clientId, scopes, userPrompt)`
5.  `clientViaUserConsentManual(clientId, scopes, userPrompt)`

**Comment by jonasfj** [comment]
Is your `GoogleSignInAccount` from package [google_sign_in](https://pub.dartlang.org/packages/google_sign_in)?

Probably you can use `https://pub.dartlang.org/documentation/googleapis_auth/latest/googleapis_auth.auth/authenticatedClient.html`

**Comment by ElixirMike** [comment]
The link above doesn't provide if/how you can use the GoogleSignInAccount.authHeaders. Is it possible? i have already implemented the Google-Signin, seems that should be enought to call the API's. I can do so through the http client request passing them as headers

**Comment by jonasfj** [comment]
Something along the lines of:
```dart

final auth = await googleSignInAccount.authentication;
final client = googleapis_auth.authenticatedClient(http.Client(), googleapis_auth.AccessCredentials(
  auth.accessToken, null, [/* scopes*/],
));
```

I haven't tested it, but that's just my guess.

**Comment by ElixirMike** [comment]
Which package do I need to import to get the AuthenciatedClient? I tried 'package:googleapis_auth/auth_browser.dart'; and 'package:googleapis_auth/auth_io.dart';

**Comment by jonasfj** [comment]
`googleapis_auth.authenticatedClient` is from `package:googleapis_auth`, see:
https://pub.dev/documentation/googleapis_auth/latest/googleapis_auth.auth/authenticatedClient.html

**Comment by fluentfuture** [comment]
This seems to work for me:

```

import 'package:googleapis/cloudresourcemanager/v1.dart'
    show Project, CloudresourcemanagerApi;
import 'package:google_sign_in/google_sign_in.dart'
    show GoogleSignIn;
import 'package:http/io_client.dart';
import 'package:http/http.dart';

Future<List<Project>> listMyProjects() async {
  final _googleSignIn = GoogleSignIn(
    scopes: [
      ...
    ],
  );

  await _googleSignIn.signIn();

  final authHeaders = await _googleSignIn.currentUser.authHeaders;

  // custom IOClient from below
  final client = GoogleHttpClient(authHeaders);
  final response = await CloudresourcemanagerApi(client)
      .projects
      .list()
      .whenComplete(client.close);
  return response.projects;
}

class GoogleHttpClient extends IOClient {
  final Map<String, String> _headers;

  GoogleHttpClient(this._headers);

  @override
  Future<StreamedResponse> send(BaseRequest request) =>
      super.send(request..headers.addAll(_headers));
}
```

**Comment by kevmoo** [comment]
See https://pub.dev/packages/extension_google_sign_in_as_googleapis_auth
