### ISSUE TITLE
Request google custom search API using user credentials received from google sign in

### ISSUE THREAD

**Issue by mnakka** [google/googleapis.dart#87]
I'm building a flutter mobile app which queries google custom search API. Currently I'm using an API Key that I got from google developer console. But that has a query limit of 100 free requests per day and have to pay after that. Using my account for all my users queries is cost ineffective. In order to address that I want my users to sign-in using google hoping that app could use their access_token to query google API and potentially each user will have their 100 free requests limits. 

But I cannot find any examples in creating a google client using access_token. Any suggestions would be appreciated. Thanks.

**Comment by kevmoo** [comment]
I'd dig in here: https://developers.google.com/custom-search/v1/introduction

Let me know if you make progress.
