### ISSUE TITLE
Error Login Required

### ISSUE THREAD

**Issue by teshlya** [google/googleapis.dart#90]
I have problem sending an email in Flutter REST API:
`{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "required",
    "message": "Login Required",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Login Required"
 }
}
`

My code:
```
String url =
        'https://www.googleapis.com/gmail/v1/users/******@gmail.com/messages/send';
Map<String, String> headers = {
      "key": "AIzaSyBtTsSfiSZwh-MivNkMYUNORaK9LIS****",
      "access_token":
          "************-3db4k5kc5qjjvbpbto5i9i9bhf54o1l3.apps.googleusercontent.com",
      "Content-type": "application/json"
    };
String json =
        '{"raw" : "RnJvbTogPHRlc2hseWFtaXNoYUBnbWFpbC5jb20+IApUbzogPHRlc2hseWFtaXNoYUBnbWFpbC5jb20+IApTdWJqZWN0OiBTYXlpbmcgSGVsbG8gVGhpcyBpcyBhIG1lc3NhZ2UganVzdCB0byBzYXkgaGVsbG8uIFNvLCAiSGVsbG8iLgoKVGhpcyBpcyB0aGUgSFRNTCBtZXNzYWdlIGJvZHk="';

Response response = await post(url, headers: headers, body: json);
print(response.body);
```

**Comment by abampalexnder** [comment]
I have got solution for google after 3 weeks brain storming and spent all day and night time to resolve the issue

any one need solution can contact on wire @abampalxender

**Comment by kevmoo** [comment]
I'd recommend using `google_sign_in` package.

See the docs here: https://flutter.dev/docs/development/data-and-backend/google-apis
