### ISSUE TITLE
[ FirestoreApi ] How to add Authorization header to the client that FirestoreApi consume

### ISSUE THREAD

**Issue by Errechydy** [google/googleapis.dart#94]
I have this rule in my firestore `allow write: if request.auth.uid == 123;`, how can i add autorization header to the client that FirestoreApi consume?
```
final client = http.Client();
final firestore = FirestoreApi(client);
await firestore.projects.databases.documents.delete(path);
```

**Comment by kevmoo** [comment]
My understanding is that this API is meant for admin usage – so it skips the Firestore rules entirely.
